{% include 'header.phtml' %}
<div id='content'>

<script type="text/javascript" src="../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../scripts/validation/site/form.contact.validation.js"></script>
    <div class="validation">{{ message }}</div>
    <form action="contact.php" method="post" id="formcontact">
        <div class="contact">
        	<p>E-mail:</p>
          <input type="text" id="email" name="email"/>
          <p>Text:</p>
            <textarea class="question" id="question" name="question" rows="5" cols="60" onfocus="if(this.value==this.defaultValue)this.value='';">Insert your question here.</textarea>
        </div>
        <input class="invio" type="submit" value="Send"/>
    </form>
</div>
{% include 'footer.phtml' %}