{% include 'header.phtml' %}

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB99tx-VW27RMBJxGIQi96sfZ89Q870K5c&sensor=true"></script>
<script type="text/javascript" src="../scripts/jquery.gomap-1.3.2.min.js"></script> 
<script type="text/javascript">
$(function() { 
    $("#map-canvas").goMap({ 
        markers: [{  
            latitude: 45.402851, 
            longitude: 11.929473,
            html: { 
                content: 'Mela Rossa', 
                popup: true 
            }
        }],
        maptype: 'roadmap',
        zoom: 16
    }); 
}); 
</script>

<div id="map-canvas"></div>

{% include 'footer.phtml' %}