{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<link rel="stylesheet" type="text/css" href="../style/jquery.bxslider.css"/>
<script type="text/javascript" src="../scripts/jquery.bxslider.min.js"></script>

<script type="text/javascript">
    $(function() {
        $('#slider1').bxSlider({
            mode: 'fade',
            auto: true,
            autoControls: true,
            pause: 5000,
            captions: true
        });
    });
</script>
<div id="content">
    <div id="sliderContainer">
        <ul id="slider1">
           {% for img in images %}
            <li><img src="{{ img.path }}"/></li>
            {% endfor %}
        </ul>
    </div>
    <h3>Mela Rossa Cash n Carry</h3>
    <p>That night another invisible missile started on its way to the earth from 
        Mars, just a second or so under twenty-four hours after the first one. I remember 
        how I sat on the table there in the blackness, with patches of green and crimson 
        swimming before my eyes. I wished I had a light to smoke by, little suspecting the 
        meaning of the minute gleam I had seen and all that it would presently bring me. 
        Ogilvy watched till one, and then gave it up; and we lit the lantern and walked over to 
        his house. Down below in the darkness were Ottershaw and Chertsey and all their hundreds of 
        people, sleeping in peace.
        He was full of speculation that night about the condition of Mars, and scoffed at the 
        vulgar idea of its having inhabitants who were signalling us. His idea was that 
        meteorites might be falling in a heavy shower upon the planet, or that a huge volcanic 
        explosion was in progress. He pointed out to me how unlikely it was that organic 
        evolution had taken the same direction in the two adjacent planets.
        "The chances against anything manlike on Mars are a million to one," he said.
        Hundreds of observers saw the flame that night and the night after about midnight, 
        and again the night after; and so for ten nights, a flame each night. Why the shots 
        ceased after the tenth no one on earth has attempted to explain. It may be the gases
        of the firing caused the Martians inconvenience. Dense clouds of smoke or dust, 
        visible through a powerful telescope on earth as little grey, fluctuating patches, 
        spread through the clearness of the planet's atmosphere and obscured its more familiar features.
        One night (the first missile then could scarcely have been 10,000,000 miles away) I 
        went for a walk with my wife. It was starlight and I explained the Signs of the 
        Zodiac to her, and pointed out Mars, a bright dot of light creeping zenithward, towards
        which so many telescopes were pointed. It was a warm night. Coming home, a party of 
        excursionists from Chertsey or Isleworth passed us singing and playing music. There 
        were lights in the upper windows of the houses as the people went to bed. From the railway 
        station in the distance came the sound of shunting trains, ringing and rumbling, softened 
        almost into melody by the distance. My wife pointed out to me the brightness of the red, 
        green, and yellow signal lights hanging in a framework against the sky. It seemed so safe and tranquil.
    </p>
</div>
{% include 'footer.phtml' %}