{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<link rel="stylesheet" type="text/css" href="../style/jflow.style.css"/>
<script type="text/javascript" src="../scripts/jflow.plus.min.js"></script>

<script type="text/javascript">
    $(function() {
        $("#myController").jFlow({
            controller: ".jFlowControl", // must be class, use . sign
            slideWrapper: "#jFlowSlider", // must be id, use # sign
            slides: "#mySlides", // the div where all your sliding divs are nested in
            selectedWrapper: "jFlowSelected", // just pure text, no sign
            effect: "flow", //this is the slide effect (rewind or flow)
            width: "690px", // this is the width for the content-slider
            height: "340px", // this is the height for the content-slider
            duration: 400, // time in milliseconds to transition one slide
            pause: 3000, //time between transitions
            prev: ".jFlowPrev", // must be class, use . sign
            next: ".jFlowNext", // must be class, use . sign
            auto: true
        });
    });
</script>
<div id="content">
    <div id="sliderContainer">
        <div id="mySlides">
            {% for img in images %}
            <div id="slide1" class="slide"><img src="{{ img.path }}"/>

                <div class="slideContent">
                    
                </div>
            </div>
            {% endfor %}
        </div>
        <div id="myController">
            {% for img in images %}
                <span class="jFlowControl"></span>
            {% endfor %}
        </div>
        <div class="jFlowPrev"></div>
        <div class="jFlowNext"></div>
    </div>
    <h3>Mela Rossa Cash n Carry</h3>
    <p>That night another invisible missile started on its way to the earth from 
        Mars, just a second or so under twenty-four hours after the first one. I remember 
        how I sat on the table there in the blackness, with patches of green and crimson 
        swimming before my eyes. I wished I had a light to smoke by, little suspecting the 
        meaning of the minute gleam I had seen and all that it would presently bring me. 
        Ogilvy watched till one, and then gave it up; and we lit the lantern and walked over to 
        his house. Down below in the darkness were Ottershaw and Chertsey and all their hundreds of 
        people, sleeping in peace.
        He was full of speculation that night about the condition of Mars, and scoffed at the 
        vulgar idea of its having inhabitants who were signalling us. His idea was that 
        meteorites might be falling in a heavy shower upon the planet, or that a huge volcanic 
        explosion was in progress. He pointed out to me how unlikely it was that organic 
        evolution had taken the same direction in the two adjacent planets.
        "The chances against anything manlike on Mars are a million to one," he said.
        Hundreds of observers saw the flame that night and the night after about midnight, 
        and again the night after; and so for ten nights, a flame each night. Why the shots 
        ceased after the tenth no one on earth has attempted to explain. It may be the gases
        of the firing caused the Martians inconvenience. Dense clouds of smoke or dust, 
        visible through a powerful telescope on earth as little grey, fluctuating patches, 
        spread through the clearness of the planet's atmosphere and obscured its more familiar features.
        One night (the first missile then could scarcely have been 10,000,000 miles away) I 
        went for a walk with my wife. It was starlight and I explained the Signs of the 
        Zodiac to her, and pointed out Mars, a bright dot of light creeping zenithward, towards
        which so many telescopes were pointed. It was a warm night. Coming home, a party of 
        excursionists from Chertsey or Isleworth passed us singing and playing music. There 
        were lights in the upper windows of the houses as the people went to bed. From the railway 
        station in the distance came the sound of shunting trains, ringing and rumbling, softened 
        almost into melody by the distance. My wife pointed out to me the brightness of the red, 
        green, and yellow signal lights hanging in a framework against the sky. It seemed so safe and tranquil.
        Then came the night of the first falling star. It was seen early in the morning, rushing 
        over Winchester eastward, a line of flame high in the atmosphere. Hundreds must have seen 
        it, and taken it for an ordinary falling star. Albin described it as leaving a greenish 
        streak behind it that glowed for some seconds. Denning, our greatest authority on meteorites, 
        stated that the height of its first appearance was about ninety or one hundred miles. 
        It seemed to him that it fell to earth about one hundred miles east of him.
        I was at home at that hour and writing in my study; and although my French windows 
        face towards Ottershaw and the blind was up (for I loved in those days to look up at the night sky), 
        I saw nothing of it. Yet this strangest of all things that ever came to earth from outer
        space must have fallen while I was sitting there, visible to me had I only looked up as 
        it passed. Some of those who saw its flight say it travelled with a hissing sound. I myself
        heard nothing of that. Many people in Berkshire, Surrey, and Middlesex must have seen the
        fall of it, and, at most, have thought that another meteorite had descended. No one seems 
        to have troubled to look for the fallen mass that night.
        But very early in the morning poor Ogilvy, who had seen the shooting star and who was persuaded
        that a meteorite lay somewhere on the common between Horsell, Ottershaw, and Woking, rose early
        with the idea of finding it. Find it he did, soon after dawn, and not far from the sand pits. 
        An enormous hole had been made by the impact of the projectile, and the sand and gravel had been
        flung violently in every direction over the heath, forming heaps visible a mile and a half away. 
        The heather was on fire eastward, and a thin blue smoke rose against the dawn.
        The Thing itself lay almost entirely buried in sand, amidst the scattered splinters of a fir tree
        it had shivered to fragments in its descent. The uncovered part had the appearance of a huge cylinder,
        caked over and its outline softened by a thick scaly dun-coloured incrustation. It had a diameter of 
        about thirty yards. He approached the mass, surprised at the size and more so at the shape, since most 
        meteorites are rounded more or less completely. It was, however, still so hot from its flight through 
        the air as to forbid his near approach. A stirring noise within its cylinder he ascribed to the unequal 
        cooling of its surface; for at that time it had not occurred to him that it might be hollow.
    </p>
</div>
{% include 'footer.phtml' %}