{% include 'user/structure/header.phtml' %}

<script>
    $(document).ready(function () {
        $('#regio').change(function () {
            $('#div2').empty();
            $('#div3').empty();
            $.get("getProv.php?id=" + $('#regio').val(), function (datas) {
                $('#div2').append('{% trans 'prov' %}<select name="prov" id="prov"></select>');
                $('#prov').append('<option selected="" disabled="" hidden="" value="">{% trans 'provs' %}</option>');
                $.each(datas, function (i, data) {
                    $('#prov').append('<option value=' + data.id + '>' + data.nome + '</option>');
                });
                $('#page').trigger('create');
                $('#prov').change(function () {
                    $('#div3').empty();
                    $.get("getCom.php?id=" + $('#prov').val(), function (datas) {
                        $('#div3').append('{% trans 'com' %}<select name="com" id="com"></select>');
                        $('#com').append('<option selected="" disabled="" hidden="" value="">{% trans 'coms' %}</option>');
                        $.each(datas, function (i, data) {
                            $('#com').append('<option value=' + data.id + '>' + data.nome + '</option>');
                        });
                        $('#page').trigger('create');
                        $('#com').change(function () {
                            $('#div3').append('<input class="invio" type="submit" value="{% trans "submit" %}"/>');
                            $('#page').trigger('create');
                        });
                    }, "json");
                });
            }, "json");
        });
    })
</script>


<div id='content'>
    <p class="detail_adm">
        {% trans "ins" %} {% trans "cust" %}
    </p>
    <p>
        {{ message }}
    </p>
    <form action="addClient.php" method="post" id="formproduct" enctype="multipart/form-data">
        {% trans "name" %}
        <input type="text" name="name"/>
        {% trans "mail" %}
        <input type="text" name="mail"/>
        {% trans "adr" %}
        <input type="text" name="address"/>
        {% trans "zcod" %}
        <input type="text" name="zcod"/>
        {% trans "piva" %}
        <input type="text" name="piva"/>
        {% trans "codf" %}
        <input type="text" name="codfis"/>

        <div id="div1">
            {% trans 'regio' %}
            <select name="regio" id="regio">
                <option selected disabled hidden value=''>{% trans 'regios' %}</option>
                {% for regio in regios %}
                <option value="{{ regio.id }}">{{ regio.nome }}</option>
                {% endfor %}
            </select>
        </div>
        <div id="div2"></div>
        <div id="div3"></div>
    </form>
</div>
{% include 'user/structure/footer.phtml' %}