{% include 'user/structure/header.phtml' %}
{% if message == 'old.ord' %}
<script>
    $(document).ready(function () {
        alert("{% trans 'old.ord' %}");
    })
</script>
{% endif %}
<div id='content'>

    <p>
        {% trans "welcome" %} <b>{{ pSession.user.name }}</b>, {% trans "welcome_2_usr" %}
    </p>
    {% if message=='old.ord' %}
    <a href="../products/catalog.php" data-role="button" data-icon="add" data-theme="a">{% trans "continue" %} {% trans
        "ord"
        %}</a>
    {% endif %}

    <a href="../actions/changeClient.php" data-role="button" data-icon="add" data-theme="a">{% trans "change.client"
        %}</a>
    {% if message=='' %}
    <a href="../products/catalog.php" data-role="button" data-icon="add" data-theme="a">{% trans "new" %} {% trans "ord"
        %}</a>
    {% endif %}
    {% if cli=='ok' %}
    <a href="../quotation/list.php" data-role="button" data-icon="check" data-theme="a">{% trans "confirm" %} {% trans
        "prevs"
        %}</a>
    {% endif %}
</div>

{% include 'user/structure/footer.phtml' %}