{% include 'user/structure/header.phtml' %}

<div id='content'>

    <p>
        {% trans "welcome" %} <b>{{ pSession.user.name }}</b>, {% trans "welcome_2_usr" %}
    </p>
    <a href="newOrder.php" data-role="button" data-icon="add" data-theme="a">{% trans "new" %} {% trans "ord" %}</a>
    <a href="confirmOrder.php" data-role="button" data-icon="check" data-theme="a">{% trans "confirm" %} {% trans "ord" %}</a>

</div>

{% include 'user/structure/footer.phtml' %}