{% include 'user/structure/header.phtml' %}
{% include 'user/structure/menu.phtml' %}
<div id='content'>
    <script type="text/javascript">
//        metodo interessante, ma da vedere perchè non funziona
//        $('.confirmation').on('click', function() {
//            return confirm('Are you sure to delete your account???');
//        });
    </script>
    <table class="tablelist">
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Address</th>
            <th>Email</th>
            <th>Telephone</th>
            <th>Cellphone</th>
            <th>Active</th>
            <th>Operator</th>
            <th>Type</th>
        </tr>
        <tr>
            <td>{{ cus.name }}</td>
            <td>{{ cus.surname }}</td>
            <td>{{ cus.address }}</td>
            <td>{{ cus.email }}</td>
            <td>{{ cus.telephone }}</td>
            <td>{{ cus.cellphone }}</td>
            <td>{{ cus.active }}</td>
            <td>{{ cus.operator }}</td>
            <td>{{ cus.type }}</td>
            <td class="delete"><a href='delete.php?id={{ cus.id }}' onclick="return confirm('Are you sure to delete your account???')"><img src="../../../images/icons/delete/delete-256.png" alt="Delete"></a></td>
            <td class="edit"><a href='prepareUpdate.php?id={{ cus.id }}'><img src="../../../images/icons/edit/edit-256.png" alt="Edit"></a></td>
        </tr>
    </table>
</div>
{% include 'user/structure/footer.phtml' %}
