{% include 'user/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "your" %} {% trans "prof" %}
	</p>
	<script type="text/javascript">
		//        metodo interessante, ma da vedere perchè non funziona
		//        $('.confirmation').on('click', function() {
		//            return confirm('Are you sure to delete your account???');
		//        });
	</script>

	<p>
		{% trans "name" %}: {{ cus.name }}
	</p>
	<p>
		{% trans "sur" %}: {{ cus.surname }}
	</p>
	{% if cus.cod_fis != '' %}
	<p>
		{% trans "codf" %}: {{ cus.cod_fis }}
	</p>
	{%endif%}
	{% if cus.piva != '' %}
	<p>
		{% trans "piva" %}: {{ cus.piva }}
	</p>
	{%endif%}
	<p>
		{% trans "adr" %}: {{ cus.address }}
	</p>
	<p>
		{% trans "mail" %}: {{ cus.email }}
	</p>
	<p>
		{% trans "tel" %}: {{ cus.telephone }}
	</p>
	<p>
		{% trans "cel" %}: {{ cus.cellphone }}
	</p>
	<p>
		{% trans "act" %}: {{ cus.active }}
	</p>
	<p>
		{% trans "op" %}: {{ cus.operator }}
	</p>
	<p>
		{% trans "type" %}: {{ cus.type }}
	</p>

	<a data-role="button" href='delete.php?id={{ cus.id }}' onclick="return confirm('{% trans "del.profile" %}')"><img src="../../../images/icons/delete/delete-256.png" height="50px" alt='{% trans "del" %}'></a>
	<!-- commentato perchè non vuole modifica utenti, ma noi lo teniamo -->
	<!-- <td class="edit"><a href='prepareUpdate.php?id={{ cus.id }}'><img src="../../../images/icons/edit/edit-256.png" alt='{% trans "edit" %}'></a></td> -->

	<p class="detail_add">
		{% trans "adrs" %}
	</p>

	<a data-role="button" href='prepareInsert_address.php?cus_id={{ cus.id }}'><img height="50px" alt='{% trans "ins" %} {% trans "new" %} {% trans "adr" %}' src="../../../images/icons/Adds/add_list/add_list-256.png"></a>

	<table data-role="table" data-mode="columntoggle">
		<thead>
			<th>{% trans "street" %}</th>
			<th>{% trans "city" %}</th>
			<th>{% trans "prov" %}</th>
			<th>{% trans "zip" %}</th>
			<th>{% trans "country" %}</th>
		</thead>
		<tbody>

			{% for addr in addrs %}
			<tr>
				<td>{{ addr.street }}</td>
				<td>{{ addr.city }}</td>
				<td>{{ addr.province }}</td>
				<td>{{ addr.zip }}</td>
				<td>{{ addr.country }}</td>
				<td class="delete"><a href='delete_address.php?cus_id={{ cus.id }}&id={{ addr.id }}'><img width="50%" src="../../../images/icons/delete/delete-256.png" alt='{% trans "del" %}'></a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% include 'user/structure/footer.phtml' %}
