{% include 'user/structure/header.phtml' %}
<script type="text/javascript" src="../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../scripts/validation/user/form.user.validation.js"></script>
<script type="text/javascript">
function toggleCf(){
    $('#cf_div').show();
    $('#piva_div').hide();
}
function togglePiva(){
    $('#cf_div').hide();
    $('#piva_div').show();
}
</script>
<div id='content'>
	<form action="register.php" method="post" style="padding-left: 270px;" id="formcustomers" enctype="multipart/form-data">
                Account type:<br>
                <input type="radio" name="account_type" value="2" onclick="toggleCf()">Normal User<br>
                <input type="radio" name="account_type" value="1" onclick="togglePiva()">Merchant<br>
		<div class="totwidth">
			<div class="panleft">
				Name:
			</div>
			<div class="panleft">
				<input type="text" id="name" name="name"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Surname:
			</div>
			<div class="panleft">
				<input type="text" id="surname" name="surname"/>
			</div>
		</div>
                <br>
                <div class="totwidth" id="cf_div" style="display: none">
			<div class="panleft">
				Cod Fiscale:
			</div>
			<div class="panleft">
				<input type="text" id="cod_fis" name="cod_fis"/>
			</div>
		</div>
		<br>
                <div class="totwidth" id="piva_div" style="display: none">
			<div class="panleft">
				P.IVA:
			</div>
			<div class="panleft">
				<input type="text" id="piva" name="piva"/>
			</div>
		</div>
                <br>
		<div class="totwidth">
			<div class="panleft">
				Address:
			</div>
			<div class="panleft">
				<input type="text" id="address" name="address"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Email:
			</div>
			<div class="panleft">
				<input type="text" id="email" name="email"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Telephone:
			</div>
			<div class="panleft">
				<input type="text" id="telephone" name="telephone"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Cellphone:
			</div>
			<div class="panleft">
				<input type="text" id="cellphone" name="cellphone"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Password:
			</div>
			<div class="panleft">
				<input type="password" id="password" name="password"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Repeat Password:
			</div>
			<div class="panleft">
				<input type="password" id="password2" name="password2"/>
			</div>
		</div>
		<br>
                <div class="totwidth">
			<div class="panleft">
				Type:
			</div>
			<div class="panleft">
				<select name="type">
					<option value="user">user</option>
					<option value="seller">seller</option>
					<option value="other">other</option>
				</select>
			</div>
		</div>
		<br>
		<br>

		<input type="submit" value="invio"/>

	</form>
</div>
{% include 'user/structure/footer.phtml' %}
