{% include 'user/structure/header.phtml' %}
<script type="text/javascript" src="../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../scripts/validation/user/form.user.validation.js"></script>
<script type="text/javascript">
    $(function() {
        if ($('#type').val() === 'user') {
            $('#cf_div').show();
            $('#piva_div').hide();

            $('#cod_fis').rules('add', {required: true});
            $('#piva').rules('remove');
        } else {
            $('#cf_div').hide();
            $('#piva_div').show();

            $('#cod_fis').rules('remove');
            $('#piva').rules('add', {required: true});
        }
    });
    function toggleDivs() {
        if ($('#type').val() === 'user') {
            $('#cf_div').show();
            $('#piva_div').hide();

            resetRequirements();
            $('#cod_fis').rules('add', {required: true});
        } else {
            $('#cf_div').hide();
            $('#piva_div').show();

            resetRequirements();
            $('#piva').rules('add', {required: true});
        }
    }

    function resetRequirements() {
        $('#cod_fis').rules('remove');
        $('#piva').rules('remove');
    }
</script>
<div id='content'>
    {{ message }}
    <form action="register.php" method="post" id="formuser">
        <div class="totwidth">
            <div class="panleft1">
                Name:
            </div>
            <div class="panleft2">
                <input type="text" id="name" name="name"/>
            </div>
        </div>
        <div class="totwidth">
            <div class="panleft1">
                Surname:
            </div>
            <div class="panleft2">
                <input type="text" id="surname" name="surname"/>
            </div>
        </div>
        <div class="totwidth" id="cf_div" style="display: none">
            <div class="panleft1">
                Cod Fiscale:
            </div>
            <div class="panleft2">
                <input type="text" id="cod_fis" name="cod_fis"/>
            </div>
        </div>
        <div class="totwidth" id="piva_div" style="display: none">
            <div class="panleft1">
                P.IVA:
            </div>
            <div class="panleft2">
                <input type="text" id="piva" name="piva"/>
            </div>
        </div>
        <div class="totwidth">
            <div class="panleft1">
                Address:
            </div>
            <div class="panleft2">
                <input type="text" id="address" name="address"/>
            </div>
        </div>
        <div class="totwidth">
            <div class="panleft1">
                Email:
            </div>
            <div class="panleft2">
                <input type="text" id="email" name="email"/>
            </div>
        </div>
        <div class="totwidth">
            <div class="panleft1">
                Telephone:
            </div>
            <div class="panleft2">
                <input type="text" id="telephone" name="telephone"/>
            </div>
        </div>
        <div class="totwidth">
            <div class="panleft1">
                Cellphone:
            </div>
            <div class="panleft2">
                <input type="text" id="cellphone" name="cellphone"/>
            </div>
        </div>
        <div class="totwidth">
            <div class="panleft1">
                Password:
            </div>
            <div class="panleft2">
                <input type="password" id="password" name="password"/>
            </div>
        </div>
        <div class="totwidth">
            <div class="panleft1">
                Repeat Password:
            </div>
            <div class="panleft2">
                <input type="password" id="password2" name="password2"/>
            </div>
        </div>
        <div class="totwidth">
            <div class="panleft1">
                Type:
            </div>
            <div class="panleft2">
                <select id="type" name="type" onchange="toggleDivs();">
                    <option value="user">user</option>
                    <option value="merchant">merchant</option>
                    <option value="stockist">stockist</option>
                </select>
            </div>
        </div>
        I agree <input  type="radio" name="agree" value="agree">

        <div class="privacy">
            {{ var }}
        </div>
        <input class="invio" type="submit" value="Invio"/>
    </form>
</div>
{% include 'user/structure/footer.phtml' %}
