{% include 'user/structure/header.phtml' %}

<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/user/form.user.validation.js"></script>
<div id='content'>
	<p class="detail_adm">{% trans "upd" %} {% trans "prof" %}</p>
    <p>{{ message }}</p>
    <form action="update.php" method="post" id="formuser">
        <input type="hidden" name="id" value="{{ usr.id }}"/>
        <div class="totwidth">
			<div class="panleft1">
				{% trans "name" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="name" value="{{ usr.name }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "sur" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="surname" value="{{ usr.surname }}"/>
			</div>
		</div>
                {% if usr.cod_fis != '' %}
                <div class="totwidth" id="cf_div">
			<div class="panleft1">
				{% trans "codf" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="cod_fis" name="cod_fis" value="{{ usr.cod_fis }}"/>
			</div>
		</div>
                {%endif%}
                {% if usr.piva != '' %}
                <div class="totwidth" id="piva_div">
			<div class="panleft1">
				{% trans "piva" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="piva" name="piva" value="{{ usr.piva }}"/>
			</div>
		</div>
                {%endif%}
		<div class="totwidth">
			<div class="panleft1">
				{% trans "adr" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="address" value="{{ usr.address }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "mail" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="email" value="{{ usr.email }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "tel" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="telephone" value="{{ usr.telephone }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "cel" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="cellphone" value="{{ usr.cellphone }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "psw" %}:
			</div>
			<div class="panleft2">
				<input id="password" type="password" name="password"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "rep" %} {% trans "psw" %}:
			</div>
			<div class="panleft2">
				<input type="password" id="password2" name="password2"/>
			</div>
		</div>
		<input class="invio" type="submit" value='{% trans "submit" %}'/>
    </form>
</div>
    {% include 'user/structure/footer.phtml' %}
