{% include 'user/structure/header.phtml' %}

<div class="login">
    <p>{{ message }}</p>
    <form method="post" action="authenticate.php">
        <input type="hidden" name="order" value="{{ order }}"/>
        <p>Email</p>
        <input type="text" name="email"/>
        <br>
        <p>Password</p>
        <input type="password" name="password"/>
        <br>
        <input type="submit" value="invio" />

    </form>
    <a href="sign_up.php">Sign up</a>
</div>
