{% include 'user/structure/header.phtml' %}

<div class="login">
    <p class="invalid">{{ message }}</p>
    <form method="post" action="authenticate.php">
        <input class="sign" type="hidden" name="order" value="{{ order }}"/>
        <p class="sign">{% trans "mail" %}:</p>
        <input class="sign_text" type="text" name="email"/>
        <p class="sign">{% trans "psw" %}:</p>
        <input class="sign_text" type="password" name="password"/>
     <input class="sign-in" type="submit" value='{% trans "signin" %}' />
	<input class="sign-up" type="button" value='{% trans "signup" %}' onclick="location.href='sign_up.php';"/>
    </form>
</div>
{% include 'user/structure/footer.phtml' %}
