{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
    <p>
        {{ message }}
    </p>
    {% if data|length > 0 %}
    <table class="tablelist">
        <tr>
            <th>{% trans "name" %}</th>
            <th>{% trans "descr" %}</th>
            <th>{% trans "piva" %}</th>
            <th>{% trans "tel" %}</th>
            <th>{% trans "fax" %}</th>
            <th>{% trans "adr" %}</th>

        </tr>
        {% for d in data %}
        <tr>
            <td><a href='show.php?id={{ d.id }}'>{{ d.name }}</a></td>
            <td>{{ d.description }}</td>
            <td>{{ d.piva }}</td>
            <td>{{ d.telephone }}</td>
            <td>{{ d.fax }}</td>
            <td>{{ d.address }}</td>
            <td class="edit"><a href='prepareUpdate.php?id={{ d.id }}'><img src="../../../images/icons/edit/edit-256.png" alt='{% trans "edit" %}'></a></td>
            <td class="add_img"><a href='addImage.php?id={{ d.id }}'><img src="../../../images/icons/add_image/add_image-256.png" alt="Add_img"></a></td>
            <td class="view_img"><a href='viewImages.php?id={{ d.id }}'><img src="../../../images/icons/gallery/gallery-256.png" alt="View_img"></a></td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>

{% include 'admin/structure/footer.phtml' %}