{% include 'header.phtml' %}
<div id='content'>

	{% include 'admin/menu.phtml' %}
	<p>
		{{ message }}
	</p>
	{% if data|length > 0 %}
	<table class="tablelist" style='margin: 50px;'>
		<tr>
			<td>Name</td>
			<td>Description</td>
			<td>P. IVA</td>
                        <td>Telephone</td>
                        <td>Fax</td>
                        <td>Address</td>
                        
		</tr>
		{% for d in data %}
		<tr>
			<td><a href='show.php?id={{ d.id }}'>{{ d.name }}</a></td>
			<td>{{ d.description }}</td>
			<td>{{ d.piva }}</td>
                        <td>{{ d.telephone }}</td>
                        <td>{{ d.fax }}</td>
                        <td>{{ d.address }}</td>
			<td><a href='prepareUpdate.php?id={{ d.id }}'>modifica</a></td>
		</tr>
		{% endfor %}
	</table>
	{% endif %}
</div>

{% include 'admin/footer.phtml' %}

