{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.company.validation.js"></script>
<div id='content'>
	<form action="update.php" method="post" id="formcompany">
		<input type="hidden" name="id" value="{{ company.id }}"/>
		<div class="totwidth">
			<div class="panleft">
				Name
			</div>
			<div class="panleft">
				<input type="text" name="name" value="{{ company.name }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft">
				Description
			</div>
			<div class="panleft">
				<input type="text" name="description" value="{{ company.description }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft">
				P. IVA
			</div>
			<div class="panleft">
				<input type="text" name="piva" value="{{ company.piva }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft">
				Telephone
			</div>
			<div class="panleft">
				<input type="text" name="telephone" value="{{ company.telephone }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft">
				Fax
			</div>
			<div class="panleft">
				<input type="text" name="fax" value="{{ company.fax }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft">
				Address
			</div>
			<div class="panleft">
				<input type="text" name="address" value="{{ company.address }}"/>
			</div>
		</div>
		<input type="submit" value="invio"/>

	</form>
</div>
{% include 'admin/structure/footer.phtml' %}
