{% include 'admin/structure/header.phtml' %}

<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.company.validation.js"></script>
<div id='content'>
	<form action="update.php" method="post" id="formcompany">
		<input type="hidden" name="id" value="{{ company.id }}"/>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "name" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="name" value="{{ company.name }}"/> <span style="font-size: 13px"> This will appear as the Header main title</span>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "descr" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="description" value="{{ company.description }}"/> <span style="font-size: 13px"> This will appear as the Header sub-title</span>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "piva" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="piva" value="{{ company.piva }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "tel" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="telephone" value="{{ company.telephone }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "fax" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="fax" value="{{ company.fax }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "adr" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="address" value="{{ company.address }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "city" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="city" value="{{ company.city }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "prov" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="province" value="{{ company.province }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "country" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="country" value="{{ company.country }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "zip" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="zip" value="{{ company.zip }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "mail" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="email" value="{{ company.email }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "site" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="website" value="{{ company.website }}"/>
			</div>
		</div>
		<input class="invio" type="submit" value='{% trans "submit" %}'/>

	</form>
</div>
{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}
