{% include 'user/administer/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "catls" %} {% trans "list" %}
	</p>
	{% if catls|length > 0 %}
	<table data-role="table" data-mode="columntoggle">
		<thead>
			<th>{% trans "name" %}</th>
		</thead>
		<tbody>
			{% for catl in catls %}
			<tr>
				<td class="first_id"><a data-role="button" data-inline="true" href='show.php?id={{ catl.id }}'>{{ catl.name }}</a></td>
				<td class="first_id"><a data-role="button" data-icon="custom" data-inline="true" id="modify" href='prepareUpdate.php?id={{ catl.id }}'>{%trans "edit"%}</a></td>
				<td class="first_id"><a data-role="button" data-icon="custom" data-inline="true" id="delete" href='delete.php?id={{ catl.id }}'>{%trans "del"%}</a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% include 'user/administer/structure/pager.phtml' %}
	{%endif%}
	{% if catls|length == 0 %}
	<p>
		{% trans "nores" %}
	</p>
	{% endif %}
</div>
{% include 'user/administer/structure/footer.phtml' %}