<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <table border='1' style='margin: 50px;'>
            <tr>
                <td>Name</td> 
                <td>Description</td>
                <td>New</td>
                <td>Offer</td>
                <td>Evidence</td>
                <td>Wholesale Price</td>
                <td>Retail Price</td>
                <td>Super Price</td>
                <td>Purchase Price</td>
                <td>Cod</td>
                <td>Barcode</td>
                <td>Single Qty</td>
                <td>Pack Qty</td>
                <td>Cardboard Qty</td>
                <td>Categoy</td>
            </tr>
            {% for prod in prods %}
            <tr>
                <td>{{ prod.name }}</td> 
                <td>{{ prod.description }}</td>
                <td>{{ prod.new }}</td>
                <td>{{ prod.offer }}</td>
                <td>{{ prod.evidence }}</td>
                <td>{{ prod.wholesale_price }}</td>
                <td>{{ prod.retail_price }}</td>
                <td>{{ prod.super_price }}</td>
                <td>{{ prod.purchase_price }}</td>
                <td>{{ prod.cod }}</td>
                <td>{{ prod.barcode }}</td>
                <td>{{ prod.single_qty }}</td>
                <td>{{ prod.pack_qty }}</td>
                <td>{{ prod.cardboard_qty }}</td>
                <td>{{ prod.categoy }}</td>
                <td><a href=''>elimina</a></td>
                <td><a href=''>modifica</a></td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>
