{% include 'header.phtml' %}
<div id='content'>
	{% include 'menu.phtml' %}
	<form action="insert.php" method="post" style="padding-left: 270px;" enctype="multipart/form-data">
		<div class="totwidth">
			<div class="panleft">
				Select a file to upload:
			</div>
			<div class="panleft">
				<input type="file" name="uploaded" id="file">
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Name:
			</div>
			<div class="panleft">
				<input type="text" name="name"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Description:
			</div>
			<div class="panleft">
				<input type="text" name="descr"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				New:
			</div>
			<div class="panleft">
				<input type="checkbox" name="new" />
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Offer:
			</div>
			<div class="panleft">
				<input type="checkbox" name="offer" />
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Evidence:
			</div>
			<div class="panleft">
				<input type="checkbox" name="evidence" />
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Wholesale Price:
			</div>
			<div class="panleft">
				<input type="text" name="w_price"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Retail Price:
			</div>
			<div class="panleft">
				<input type="text" name="r_price"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Super Price:
			</div>
			<div class="panleft">
				<input type="text" name="s_price"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Purchase Price:
			</div>
			<div class="panleft">
				<input type="text" name="p_price"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Cod:
			</div>
			<div class="panleft">
				<input type="text" name="cod"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Barcode:
			</div>
			<div class="panleft">
				<input type="text" name="barcode"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Single Qty:
			</div>
			<div class="panleft">
				<input type="text" name="s_qty"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				pack Qty:
			</div>
			<div class="panleft">
				<input type="text" name="p_qty"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Cardboard Qty:
			</div>
			<div class="panleft">
				<input type="text" name="c_qty"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Category:
			</div>
			<div class="panleft">
				<select name="cat_id">
					{% for cat in cats %}
					<option value="{{ cat.id }}">{{ cat.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<br>

		<input type="submit" value="invio"/>

	</form>
</div>
{% include 'footer.phtml' %}
