{% include 'admin/structure/header.phtml' %}

<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.product.validation.js"></script>
<script type="text/javascript">
	$(function() {
		$('#w_price').parent().contents(':not(input)').remove();
		var per = $('#w_price').val();
		var multiplier = 1 + (per / 100);
		var rw = $('#p_price').val() * multiplier;
		$('#w_price').after(parseFloat(rw).toFixed(2));

		$('#r_price').parent().contents(':not(input)').remove();
		var per = $('#r_price').val();
		var multiplier = 1 + (per / 100);
		var rr = $('#p_price').val() * multiplier;
		$('#r_price').after(parseFloat(rr).toFixed(2));

		$('#s_price').parent().contents(':not(input)').remove();
		var per = $('#s_price').val();
		var multiplier = 1 + (per / 100);
		var rss = $('#p_price').val() * multiplier;
		$('#s_price').after(parseFloat(rss).toFixed(2));
	});
	function calculate(percentage) {
		$('#' + percentage.id).parent().contents().filter(function() {
      return this.nodeType === 3;
    }).remove();
		var per = percentage.value;
		var multiplier = 1 + (per / 100);
		var rs = $('#p_price').val() * multiplier;
		$('#' + percentage.id).after(parseFloat(rs).toFixed(2));
	}

	function refreshAll() {
		calculate(document.getElementById('w_price'));
		calculate(document.getElementById('r_price'));
		calculate(document.getElementById('s_price'));
	}
</script>
<div id='content'>
	<p class="detail_adm">
		{% trans "ins" %} {% trans "prod" %}
	</p>
	<p>
		{{ message }}
	</p>
	<form action="insert.php" method="post" id="formproduct" enctype="multipart/form-data">
		<div class="totwidth">
			<div class="panleft1">
				{% trans "img" %}:
			</div>
			<div class="panleft2">
				<input type="file" name="uploaded" id="file">
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "name" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="name" name="name"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "descr" %}:
			</div>
			<textarea id="textarea" name="descr" rows="1" cols="75"></textarea>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "new" %}:
			</div>
			</br>
			<div class="panleft2">
				<input type="checkbox" name="new" />
			</div>
		</div>
		</br>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "ofr" %}:
			</div></br>
			<div class="panleft2">
				<input type="checkbox" name="offer" />
			</div>
		</div></br>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "hlg" %}:
			</div></br>
			<div class="panleft2">
				<input type="checkbox" name="evidence" />
			</div>
		</div></br>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "pur" %} {% trans "pr" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="p_price" onchange="refreshAll();" name="p_price"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "wh" %} {% trans "pr" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="w_price" onchange="calculate(this);" name="w_price"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "ret" %} {% trans "pr" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="r_price" onchange="calculate(this);" name="r_price"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "super" %} {% trans "pr" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="s_price" onchange="calculate(this);" name="s_price"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "cod" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="cod" name="cod"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "bcod" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="barcode" name="barcode"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "sng" %} {% trans "qty" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="s_qty" name="s_qty"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "pck" %} {% trans "qty" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="p_qty" name="p_qty"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "cdb" %} {% trans "qty" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="c_qty" name="c_qty"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "vat" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="vat"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "cat" %}:
			</div>
			<div class="panleft2">
				<select name="cat_id">
					{% for cat in cats %}
					<option value="{{ cat.id }}">{{ cat.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "catl" %}:
			</div>
			<div class="panleft2">
				<select name="catl_id">
					{% for catl in catls %}
					<option value="{{ catl.id }}">{{ catl.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<input class="invio" type="submit" value='{% trans "submit" %}'/>
	</form>
</div>
{% include 'admin/structure/footer.phtml' %}
