{% include 'admin/structure/header.phtml' %}
<div id='content'>

    {% include 'admin/structure/menu.phtml' %}
    {% if prods|length > 0 %}
    <table class="tablelist" style='margin: 50px;'>
        <tr>
            <td>Name</td>
            <td>Description</td>
            <td>New</td>
            <td>Offer</td>
            <td>Evidence</td>
            <td>Wholesale Price</td>
            <td>Retail Price</td>
            <td>Super Price</td>
            <td>Purchase Price</td>
            <td>Cod</td>
            <td>Barcode</td>
            <td>Single Qty</td>
            <td>Pack Qty</td>
            <td>Cardboard Qty</td>
            <td>Category</td>
        </tr>
        {% for prod in prods %}
        <tr>
            <td><a href='show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
            <td>{{ prod.description }}</td>
            <td>{{ prod.new }}</td>
            <td>{{ prod.offer }}</td>
            <td>{{ prod.evidence }}</td>
            <td>{{ prod.wholesale_price }}</td>
            <td>{{ prod.retail_price }}</td>
            <td>{{ prod.super_price }}</td>
            <td>{{ prod.purchase_price }}</td>
            <td>{{ prod.cod }}</td>
            <td>{{ prod.barcode }}</td>
            <td>{{ prod.single_qty }}</td>
            <td>{{ prod.pack_qty }}</td>
            <td>{{ prod.cardboard_qty }}</td>
            <td>{{ prod.category }}</td>
            <td><a href='delete.php?id={{ prod.id }}'>elimina</a></td>
            <td><a href='prepareUpdate.php?id={{ prod.id }}'>modifica</a></td>
        </tr>
        {% endfor %}
    </table>
        {% if totPages > 1 %}
            <a href="list.php?offset=0">First</a>
            {% set last = 0 %}
            {% for i in range(low=1, high=totPages, step=1) %}

                <a href="list.php?offset={{ i - 1}}">{{ i }}</a>
                {% set last = i -1 %}
            {% endfor %}
             <a href="list.php?offset={{ last }}">Last</a>
        {%endif%}
    {%endif%}
    {% if prods|length == 0 %}
    <p>
        no elements found
    </p>
    {% endif %}
</div>

{% include 'admin/structure/footer.phtml' %}