{% include 'admin/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "prods" %} {% trans "list" %}
	</p>
	{% if prods|length > 0 %}
	<table data-role="table" data-mode="columntoggle">
		<thead>
			<th>{% trans "name" %}</th>
			<th>{% trans "cod" %}</th>
			<th>{% trans "bcod" %}</th>

			<th>{% trans "cat" %}</th>
		</thead>
		<tbody>
			{% for prod in prods %}
			<tr>
				<td class="first_id"><a href='show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>

				<td>{{ prod.cod }}</td>
				<td>{{ prod.barcode }}</td>

				<td>{{ prod.category }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% include 'admin/structure/pager.phtml' %}
	{%endif%}
	{% if prods|length == 0 %}
	<p>
		{% trans "nores" %}
	</p>
	{% endif %}
</div>
{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}