{% include 'admin/structure/header.phtml' %}
<div id='content'>

	{% include 'admin/structure/menu.phtml' %}
        {% if prod.image != '' %}
	<img src="../../{{ prod.image }}">
        {% endif %}
	<table class="tablelist" style='margin: 50px;'>
		<tr>
			<th>Name</th>
			<th>Description</th>
			<th>New</th>
			<th>Offer</th>
			<th>Evidence</th>
			<th>Wholesale Price</th>
			<th>Retail Price</th>
			<th>Super Price</th>
			<th>Purchase Price</th>
			<th>Cod</th>
			<th>Barcode</th>
			<th>Single Qty</th>
			<th>Pack Qty</th>
			<th>Cardboard Qty</th>
			<th>Category</th>
		</tr>
		<tr>
			<td>{{ prod.name }}</td>
			<td>{{ prod.description }}</td>
			<td>{{ prod.new }}</td>
			<td>{{ prod.offer }}</td>
			<td>{{ prod.evidence }}</td>
			<td>{{ prod.wholesale_price }}</td>
			<td>{{ prod.retail_price }}</td>
			<td>{{ prod.super_price }}</td>
			<td>{{ prod.purchase_price }}</td>
			<td>{{ prod.cod }}</td>
			<td>{{ prod.barcode }}</td>
			<td>{{ prod.single_qty }}</td>
			<td>{{ prod.pack_qty }}</td>
			<td>{{ prod.cardboard_qty }}</td>
			<td>{{ prod.category }}</td>
			<td class="delete"><a href='delete.php?id={{ prod.id }}'>x</a></td>
			<td class="edit"><a href='prepareUpdate.php?id={{ prod.id }}'>[&#133;]</a></td>
		</tr>
	</table>
</div>
{% include 'admin/structure/footer.phtml' %}
