{% include 'admin/structure/header.phtml' %}

<div id='content'>
	<div class="show_adm">
		<h1 class="show_adm">{{ prod.name }}</h1>
		{% if prod.image != '' %}
		<img src="../../{{ prod.image }}" width="100%">
		{% endif %}
		<p>
			<b>{% trans "descr" %}:</b>
		</p>
		<p>
			{{ prod.description }}
		</p>
		<!--prod new-->
		<p>
			<b>{% trans "new" %}:</b>
		</p>

		{% if prod.new == 1 %}
		<p style="color:#008000">
			&#x2713;
		</p>
		{% endif %}
		{% if prod.new == 0 %}
		<p style="color:#D40303;">
			&#x2717;
		</p>
		{% endif %}

		<!--prod ofr-->
		<p>
			<b>{% trans "ofr" %}:</b>
		</p>
		{% if prod.offer == 1 %}
		<p style="color:#008000;">
			&#x2713;
		</p>
		{% endif %}
		{% if prod.offer == 0 %}
		<p style="color:#D40303;">
			&#x2717;
		</p>
		{% endif %}

		<!--prod hlg-->
		<p>
			<b>{% trans "hlg" %}:</b>
		</p>
		{% if prod.evidence == 1 %}
		<p style="color:#008000;">
			&#x2713;
		</p>
		{% endif %}
		{% if prod.evidence == 0 %}
		<p style="color:#D40303;">
			&#x2717;
		</p>
		{% endif %}

		<!--prod wh-->
		<p>
			<b>{% trans "wh" %} :&#128; {{ prod.wholesale_price }}</b>
		</p>
		<!--prod ret-->
		<p>
			<b>{% trans "ret" %} :&#128; {{ prod.retail_price }}</b>
		</p>

		<!--prod super-->
		<p>
			<b>{% trans "super" %} :&#128; {{ prod.super_price }}</b>
		</p>

		<!--prod pur-->
		<p>
			<b>{% trans "pur" %} :&#128; {{ prod.purchase_price }}</b>
		</p>

		<!--prod cod-->
		<p>
			<b>{% trans "cod" %} : {{ prod.cod }}</b>
		</p>

		<!--prod bcod-->
		<p>
			<b>{% trans "bcod" %} : {{ prod.barcode }}</b>
		</p>
		<!--prod sng-->
		<p>
			<b>{% trans "sng" %} : {{ prod.single_qty }}</b>
		</p>

		<!--prod pck-->
		<p>
			<b>{% trans "pck" %} : {{ prod.pack_qty }}</b>
		</p>

		<!--prod cdb-->
		<p>
			<b>{% trans "cdb" %} : {{ prod.cardboard_qty }}</b>
		</p>

		<!--prod vat-->
		<p>
			<b>{% trans "vat" %} : {{ prod.vat }}</b>
		</p>
		<!--prod cat-->
		<p>
			<b>{% trans "cat" %} : {{ prod.category }}</b>
		</p>
		<!--prod catl-->
		<p>
			<b>{% trans "catl" %} : {{ prod.catalog }}</b>
		</p>
		<a data-role="button" href='delete.php?id={{ prod.id }}'><img src="../../../images/icons/delete/delete-256.png" width="10%" alt='{% trans "del" %}'></a>
		<a data-role="button" href='prepareUpdate.php?id={{ prod.id }}'><img src="../../../images/icons/edit/edit-256.png" width="10%" alt='{% trans "edit" %}'></a>
	</div>

</div>
{% include 'admin/structure/footer.phtml' %}
