<div data-role="navbar" data-iconpos="top">
    <ul>
        <li><a href="../products/prepareListByCode.php" data-icon="search">{% trans "search" %} {% trans "by" %} {% trans "cod"
                %}</a></li>
        <li><a href="../products/listComplete.php" data-icon="search">{% trans "search.from.complete.list" %}</a></li>
        <li><a href="../products/prepareListByDN.php" data-icon="search">{% trans "search" %} {% trans "by" %} {% trans "name" %}/{%
                trans "descr" %}</a></li>
    </ul>
</div>