{% include 'admin/structure/header.phtml' %}

<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.invoice.validation.js"></script>
<div id='content'>
    <p class="detail_adm">{% trans "inv" %}</p>
    <form action="create_invoice.php" method="post" id="forminvoice">
        <input type="hidden" name="id" value="{{ o_id }}"/>
        <div class="totwidth">
            <div class="panleft1">
                {% trans "num" %}:
            </div>
            <div class="panleft2">
                <input type="text" name="inv_number" value="{{ inv_number }}"/>
            </div>
        </div>
        <input class="invio" type="submit" value='{% trans "submit" %}'/>
    </form>
</div>{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}
