{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
    <p class="detail_adm">{% trans "ord" %}</p>
    <p>{{ message }}</p>
    <table class="tablelist">
        <tr>
            <th>{% trans "id" %}</th>
            <th>{% trans "date" %}</th>
            <th>{% trans "confed" %}</th>
            <th>{% trans "confirm" %} {% trans "date" %}</th>
            <th>{% trans "op" %}Operator</th>
            <th>{% trans "cust" %}Customer</th>
        </tr>
        <tr>
            <td><a href='show.php?id={{ ord.id }}'>{{ ord.id }}</a></td>
            <td>{{ ord.data }}</td>
            <td>{{ ord.confirmed }}</td>
            <td>{{ ord.confirm_date }}</td>
            <td>{{ ord.operator }}</td>
            <td>{{ ord.customer }}</td>
        </tr>
        <!--vedi commento su modifche file php-->
        <!--        {% for prod in products %}
                <tr>
                    <td><a href='../products/show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
                    <td>{{ prod.quantity }}</td>
                </tr>
                {% endfor %}-->
    </table>
    {% if ord.confirmed != 1%}
    <a href='confirm.php?id={{ ord.id }}' onclick="return confirm('{% trans "conford" %}');">{% trans "confrm" %} {% trans "ord" %}</a>
    {% endif %}
    {% if ord.file != ''%}
    <li class="print">
        <a href='{{ ord.file }}'><img src="../../../images/icons/printer/printer-256.png" alt="Print">{% trans "print" %}</a>
    </li>
    <li class="pdf">
        <a href='{{ ord.file }}'><img src="../../../images/icons/pdf/pdf-256.png" alt="PDF">{% trans "pdf" %}</a>
    </li>
    {% endif %}
</div>
{% include 'admin/structure/footer.phtml' %}
