{% include 'admin/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "ord" %}
	</p>
	<p>
		{{ message }}
	</p>

	<p>
		{% trans "id" %}: <a href='show.php?id={{ ord.id }}'>{{ ord.id }}</a>
	</p>
	<p>
		{% trans "date" %}: {{ ord.data }}
	</p>
	<p>
		{% trans "confed" %}: {% if ord.confirmed == 1 %}
	<p style="color:#008000;">
		&#x2713;
	</p>
	{% endif %}
	{% if ord.confirmed == 0 %}
	<p style="color:#D40303;">
		&#x2717;
	</p>
	{% endif %}</p>
	<p>
		{% trans "confirm" %} {% trans "date" %}: {{ ord.confirm_date }}
	</p>
	<p>
		{% trans "op" %}: {{ ord.operator }}
	</p>
	<p>
		{% trans "cust" %}: {{ ord.customer }}
	</p>

	<p>
		{% trans "prods" %}
	</p>
	<table class="tablelist">
		<thead>
			<th>{% trans "name" %}</th>
			<th>{% trans "qty" %}</th>
		</thead><tbody>
		{% for prod in products %}
		<tr>
			<td><a href='../products/show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
			<td>{{ prod.quantity }}</td>
			<td class="delete"><a href='delete_product.php?o_id={{ ord.id }}&p_id={{ prod.id }}'><img width="20%" src="../../../images/icons/delete/delete-256.png" alt='{% trans "del" %}'></a></td>
		</tr>
		{% endfor %}</tbody>
	</table>
	<ul data-role="listview">
		{% if ord.confirmed != 1%}
		<li class="confirm_order">
			<a href='confirm.php?id={{ ord.id }}' onclick="return confirm('{% trans "conford" %}');"><img src="../../../images/icons/system/checkmark/checkmark-256.png" alt='{% trans "pdf" %}'>{% trans "confirm" %} {% trans "ord" %}</a>
		</li>
		{% endif %}
		{% if ord.pdf != ''%}
		<li class="pdf_invoice">
			<a href='{{ ord.pdf }}'><img src="../../../images/icons/pdf/pdf-256.png" alt='{% trans "pdf" %}'>{% trans "sho" %} {% trans "pdf" %}</a>
		</li>
		{% endif %}
		{% if ord.invoice == ''%}
		<li class="create_invoice">
			<a href='prepare_create_invoice.php?id={{ ord.id }}'><img src="../../../images/icons/accounting/purchase_order/purchase_order-256.png" alt='{% trans "crt" %}'>{% trans "crt" %} {% trans "inv" %}</a>
		</li>
		{% endif %}
		{% if ord.invoice != ''%}
		<li class="create_invoice">
			<a href='{{ ord.invoice }}'><img src="../../../images/icons/accounting/purchase_order/purchase_order-256.png" alt='{% trans "sho" %}'>{% trans "sho" %} {% trans "inv" %}</a>
		</li>
		<li class="create_invoice">
			<a href='prepare_create_invoice.php?id={{ ord.id }}'><img src="../../../images/icons/accounting/purchase_order/purchase_order-256.png" alt='{% trans "crt" %}'>{% trans "upd" %} {% trans "inv" %}</a>
		</li>
		{% endif %}
	</ul>
</div>{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}
