{% include 'admin/structure/header.phtml' %}

<div id='content'>
    <form action="update.php" method="post" id="formproduct" enctype="multipart/form-data">

        <input type="hidden" name="id" value="{{ cust.id }}"/>

        {% trans "name" %}
        <input type="text" name="name" value="{{ cust.name }}"/>
        {% trans "sur" %}
        <input type="text" name="surname" value="{{ cust.surname }}"/>
        {% trans "mail" %}
        <input type="text" name="mail" value="{{ cust.email }}"/>
        {% trans "psw" %}
        <input type="password" name="password"/>
        {% trans "adr" %}
        <input type="text" name="address" value="{{ cust.address }}"/>
        {% trans "tel" %}
        <input type="text" name="telephone" value="{{ cust.telephone }}"/>
        {% trans "cel" %}
        <input type="text" name="cellphone" value="{{ cust.cellphone }}"/>
        {% if cust.admin=='1' %}
        {% trans "admin" %}
        <input type="checkbox" name="admin" checked/>
        {% endif %}
        {% if cust.admin=='0' %}
        {% trans "admin" %}
        <input type="checkbox" name="admin"/>
        {% endif %}
        {% trans "codf" %}
        <input type="text" name="codfis" value="{{ cust.cod_fis }}"/>
        <input class="invio" type="submit" value='{% trans "submit" %}'/>

    </form>

</div>
{% include 'admin/structure/footer.phtml' %}
