<div id="footer">
    <div id="footer_inside">
        <ul class="footer_menu">
            <li>
                <a href="/MelaRossa/pages/admin/index.php">Home Page Admin Panel</a>|
            </li>
            <li>
                <a href="">Chi siamo</a>|
            </li>
            <li>
                <a href="/MelaRossa/pages/where.php">Dove siamo</a>|
            </li>
            <li>
                <a href="">Contatti</a>|
            </li>
            
            {% if pSession.user.id != ''%}
            <li>
                <a href="/MelaRossa/pages/admin/logout.php">Logout</a>
            </li>
            {% endif %}
        </ul>
        <br />
        <br />
        <p>
            Copyright &copy;. All rights reserved. Design by Giacomo Bianchetto
        </p>

    </div>
</div>