<div id="sidebar">
	<h2>Categorie</h2>
	<ul id="list">
		<li class="color">
			<a href="/melarossa/pages/admin/products/prepareInsert.php">Insert Product</a>
		</li>
		<li>
			<a href="/melarossa/pages/admin/products/list.php?offset=0">List all products</a>
		</li>
		<li class="color">
			<a href="/melarossa/pages/admin/categories/prepareInsert.php">Insert Category</a>
		</li>
		<li>
			<a href="/melarossa/pages/admin/categories/list.php">List all categories</a>
		</li>
		<li class="color">
			<a href="/melarossa/pages/admin/administrators/prepareInsert.php">Insert Admin</a>
		</li>
		<li>
			<a href="/melarossa/pages/admin/administrators/list.php">List all administrators</a>
		</li>
		<li class="color">
			<a href="/melarossa/pages/admin/customers/prepareInsert.php">Insert Customer</a>
		</li>
		<li>
			<a href="/melarossa/pages/admin/customers/list.php">List all customers</a>
		</li>
		<li class="color">
			<a href="/melarossa/pages/admin/orders/list.php">List all orders</a>
		</li>
		<li>
			<a href="/melarossa/pages/admin/company/list.php">Company Info</a>
		</li>   
	</ul>
</div>