{% include 'user/structure/header.phtml' %}
	{% include 'user/structure/menu.phtml' %}
<div id='content'>
	<p class="detail_adm">{% trans "ords" %} {% trans "list" %}</p>
	<p>{{ message }}</p>
	{% if orders|length > 0 %}
	<table class="tablelist">
		<tr>
			<th>{% trans "id" %}</th>
			<th>{% trans "date" %}</th>
			<th>{% trans "confed" %}</th>
			<th>{% trans "op" %}</th>
		</tr>
		{% for ord in orders %}
		<tr>
			<td><a href='show.php?id={{ ord.id }}'>{{ ord.id }}</a></td>
			<td>{{ ord.data }}</td>
			<td>{{ ord.confirmed }}</td>
			<td>{{ ord.operator }}</td>
		</tr>
		{% endfor %}
	</table>
            {% include 'user/structure/pager.phtml' %}
	{%endif%}
	{% if orders|length == 0 %}
	<p>
		{% trans "nores" %}
	</p>
	{% endif %}
</div>
{% include 'user/structure/footer.phtml' %}