{% include 'user/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "ords" %} {% trans "list" %}
	</p>
	<p>
		{{ message }}
	</p>
	{% if orders|length > 0 %}
	<table class="tablelist">
		<tr>
			<th>{% trans "id" %}</th>
			<th>{% trans "date" %}</th>
		</tr>
		{% for ord in orders %}
		<tr>
			<td class="first_id"><a href='show.php?id={{ ord.id }}'>{{ ord.id }}</a></td>
			<td>{{ ord.data }}</td>
		</tr>
		{% endfor %}
	</table>
	{% include 'user/structure/pager.phtml' %}
	{%endif%}
	{% if orders|length == 0 %}
	<p>
		{% trans "nores" %}
	</p>
	{% endif %}
</div>
{% include 'user/structure/footer.phtml' %}