{% include 'user/structure/header.phtml' %}
<div id='content'>

	{% include 'user/structure/menu.phtml' %}
	<p>
		{{ message }}
	</p>
	{% if orders|length > 0 %}
	<table class="tablelist" style='margin: 50px;'>
		<tr>
			<td>ID</td>
			<td>Date</td>
			<td>Confirmed</td>
			<td>Operator</td>
		</tr>
		{% for ord in orders %}
		<tr>
			<td><a href='show.php?id={{ ord.id }}'>{{ ord.id }}</a></td>
			<td>{{ ord.data }}</td>
			<td>{{ ord.confirmed }}</td>
			<td>{{ ord.operator }}</td>
		</tr>
		{% endfor %}
	</table>
	{%endif%}
	{% if orders|length == 0 %}
	<p>
		no elements found
	</p>
	{% endif %}
</div>
{% include 'user/structure/footer.phtml' %}