{% include 'user/structure/header.phtml' %}
{% include 'user/structure/menu.phtml' %}
<div id='content'>
    <p class="detail_adm">{% trans "ord" %}</p>
    <table class="tablelist">
        <tr>
            <th>{% trans "id" %}</th>
            <th>{% trans "date" %}</th>
            <th>{% trans "confed" %}</th>
            <th>{% trans "op" %}</th>
        </tr>
        <tr>
            <td><a href='show.php?id={{ ord.id }}'>{{ ord.id }}</a></td>
            <td>{{ ord.data }}</td>
            <td>{{ ord.confirmed }}</td>
            <td>{{ ord.operator }}</td>
        </tr>
        <!--vedi commento su modifche file php-->
        <!-- {% for prod in products %}
        <tr>
            <td><a href='../products/show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
            <td>{{ prod.quantity }}</td>
        </tr>
        {% endfor %}-->
    </table>
    {% if ord.file != ''%}
    <li class="print">
        <a href='{{ ord.file }}'><img src="../../../images/icons/printer/printer-256.png" alt='{% trans "print" %}'>{% trans "print" %}</a>
    </li>
    <li class="pdf">
        <a href='{{ ord.file }}'><img src="../../../images/icons/pdf/pdf-256.png" alt='{% trans "pdf" %}'>{% trans "pdf" %}</a>
    </li>
    {% endif %}
</div>
{% include 'user/structure/footer.phtml' %}
