{% include 'user/structure/header.phtml' %}
    {% include 'user/structure/menu.phtml' %}
<div id='content'>

    <table border='1' style='margin: 50px;'>
        <tr>
            <th>{% trans "id" %}</th>
            <th>{% trans "date" %}</th>
            <th>{% trans "confed" %}</th>
            <th>{% trans "op" %}</th>
        </tr>
        <tr>
            <td><a href='show.php?id={{ ord.id }}'>{{ ord.id }}</a></td>
            <td>{{ ord.data }}</td>
            <td>{{ ord.confirmed }}</td>
            <td>{{ ord.operator }}</td>
        </tr>
        <!--vedi commento su modifche file php-->
        <!-- {% for prod in products %}
        <tr>
            <td><a href='../products/show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
            <td>{{ prod.quantity }}</td>
        </tr>
        {% endfor %}-->
    </table>
    {% if ord.file != ''%}
        <a href='{{ ord.file }}'>pdf</a>
    {% endif %}
</div>
{% include 'user/structure/footer.phtml' %}
