{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="../../../scripts/form.administrators.validation.js"></script>
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<div id='content'>

	<form action="insert.php" method="post" id="formadministrators" enctype="multipart/form-data">
		<div class="totwidth">
			<div class="panleft">
				Name:
			</div>
			<div class="panleft">
				<input type="text" id="name" name="name"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				User:
			</div>
			<div class="panleft">
				<input type="text" id="user" name="user"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Password:
			</div>
			<div class="panleft">
				<input type="password" id="password" name="password"/>
			</div>
		</div>
		<br>
		<input type="submit" value="invio"/>

	</form>
</div>

{% include 'admin/structure/footer.phtml' %}
