{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.administrators.validation.js"></script>
<div id='content'>

	<form action="insert.php" method="post" id="formadministrators">
		<div class="totwidth">
			<div class="panleft1">
				Name:
			</div>
			<div class="panleft2">
				<input type="text" id="name" name="name"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				User:
			</div>
			<div class="panleft">
				<input type="text" id="user" name="user"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				Password:
			</div>
			<div class="panleft2">
				<input type="password" id="password" name="password"/>
			</div>
		</div>
		<input class="invio" type="submit" value="Invio"/>

	</form>
</div>

{% include 'admin/structure/footer.phtml' %}
