{% include 'admin/structure/header.phtml' %}
<div id='content'>

	{% include 'admin/structure/menu.phtml' %}
	<p>
		{{ message }}
	</p>
	{% if admins|length > 0 %}
	<table class="tablelist">
		<tr>
			<th>Name</th>
			<th>user</th>
		</tr>
		{% for admin in admins %}
		<tr>
			<td><a href='show.php?id={{ admin.id }}'>{{ admin.name }}</a></td>
			<td>{{ admin.user }}</td>
                        {% if admin.role != 'jack' %}
                            <td class="delete"><a href='delete.php?id={{ admin.id }}'>x</a></td>
                        {% endif %}
			<td class="edit"><a href='prepareUpdate.php?id={{ admin.id }}'>[&#133;]</a></td>
		</tr>
		{% endfor %}
	</table>
	{% endif %}
	{% if admins|length == 0 %}
	<p>
		no elements found
	</p>
	{% endif %}
</div>

{% include 'admin/structure/footer.phtml' %}

