{% include 'admin/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "adms" %}' {% trans "list" %}
	</p>
	<p>
		{{ message }}
	</p>
	{% if admins|length > 0 %}
	<table data-role="table" data-mode="columntoggle" >
		<thead>
			<th>{% trans "name" %}</th>
			<th>{% trans "usr" %}</th>
		</thead>
		<tbody>
			{% for admin in admins %}
			<tr>
				<td class="first_id"><a href='show.php?id={{ admin.id }}'>{{ admin.name }}</a></td>
				<td>{{ admin.user }}</td>
				{% if admin.role != 'jack' %}
				<td class="delete_admin"><a href='delete.php?id={{ admin.id }}'><img src="../../../images/icons/users/remove_user/remove_user-256.png" width="20%" alt='{% trans "del" %}'></a></td>
				{% endif %}
				<td class="edit_admin"><a href='prepareUpdate.php?id={{ admin.id }}'><img src="../../../images/icons/users/edit_user/edit_user-256.png" width="20%" alt='{% trans "edit" %}'></a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% include 'admin/structure/pager.phtml' %}
	{% endif %}
	{% if admins|length == 0 %}
	<p>
		{% trans "nores" %}
	</p>
	{% endif %}
</div>
{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}

