{% include 'admin/structure/header.phtml' %}
<div id='content'>

	{% include 'admin/structure/menu.phtml' %}
	<table class="tablelist" style='margin: 50px;'>
		<tr>
			<th>Name</th>
			<th>user</th>
			<th>role</th>
		</tr>
		<tr>
			<td>{{ admin.name }}</td>
			<td>{{ admin.user }}</td>
			<td>{{ admin.role }}</td>
			<td class="delete"><a href='delete.php?id={{ admin.id }}'>x</a></td>
			<td class="edit"><a href='prepareUpdate.php?id={{ admin.id }}'>[&#133;]</a></td>
		</tr>
	</table>
</div>
{% include 'admin/structure/footer.phtml' %}
