{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
	<p class="detail_adm">{% trans "adm" %}</p>
	<table class="tablelist">
		<tr>
			<th>{% trans "name" %}</th>
			<th>{% trans "usr" %}</th>
		</tr>
		<tr>
			<td>{{ admin.name }}</td>
			<td>{{ admin.user }}</td>
			<td class="delete"><a href='delete.php?id={{ admin.id }}'><img src="../../../images/icons/delete/delete-256.png" alt='{% trans "del" %}'></a></td>
			<td class="edit"><a href='prepareUpdate.php?id={{ admin.id }}'><img src="../../../images/icons/edit/edit-256.png" alt='{% trans "edit" %}'></a></td>
		</tr>
	</table>
</div>
{% include 'admin/structure/footer.phtml' %}
