{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.administrators.validation.js"></script>
<div id='content'>
	<form action="update.php" method="post" id="formadministrators">
		<input type="hidden" name="id" value="{{ admin.id }}"/>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "name" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="name" value="{{ admin.name }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "usr" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="user" value="{{ admin.user }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "psw" %}:
			</div>
			<div class="panleft2">
				<input type="password" name="password" />
			</div>
		</div>
		<input class="invio" type="submit" value='{% trans "submit" %}'/>

	</form>
</div>
{% include 'admin/structure/footer.phtml' %}
