{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
	<form action="update.php" method="post" style="padding-left: 270px;">
		<input type="hidden" name="id" value="{{ admin.id }}"/>
		<div class="totwidth">
			<div class="panleft">
				Name
			</div>
			<div class="panleft">
				<input type="text" name="name" value="{{ admin.name }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				User
			</div>
			<div class="panleft">
				<input type="text" name="user" value="{{ admin.user }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Password
			</div>
			<div class="panleft">
				<input type="password" name="password" />
			</div>
		</div>
		<br>
		<input type="submit" value="invio"/>

	</form>
</div>
{% include 'admin/structure/footer.phtml' %}
