{% include 'header.phtml' %}
<div id='content'>

	{% include 'menu.phtml' %}
			<form action="insert.php" method="post" style="padding-left: 270px;" enctype="multipart/form-data">
				Name:
				<input type="text" name="name"/>
				<br>

				Category:

				<select name="cat_id">
					{% for cat in cats %}
					<option value="{{ cat.id }}">{{ cat.name }}</option>
					{% endfor %}
				</select>

				<input type="submit" value="invio"/>

			</form>
		</div>
		<div id="footer">
			<div id="footer_inside">
				<ul class="footer_menu">
					<li>
						<a href="/MelaRossa/index.php">Home Page</a>|
					</li>
					<li>
						<a href="">Chi siamo</a>|
					</li>
					<li>
						<a href="/MelaRossa/pages/where.php">Dove siamo</a>|
					</li>
					<li>
						<a href="">Contatti</a>
					</li>
				</ul>
				<br />
				<br />
				<p>
					Copyright &copy;. All rights reserved. Design by Giacomo Bianchetto
				</p>
				<p style="float: right;">
					<a href="/MelaRossa/pages/admin/login.php">Admin</a> | <a href="/MelaRossa/pages/user/login.php">User</a>
				</p>
			</div>
		</div>
	{% include 'footer.phtml' %}
