{% include 'admin/structure/header.phtml' %} 
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.categories.validation.js"></script>
<div id='content'>

	<form action="insert.php" method="post" id="formcategories">
		<div class="totwidth">
			<div class="panleft1">
				{% trans "name" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="name" name="name"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "cat" %}:
			</div>
			<div class="panleft2">
				<select name="cat_id">
					{% for cat in cats %}
					<option value="{{ cat.id }}">{{ cat.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<input class="invio" type="submit" value='{% trans "submit" %}'/>

	</form>
</div>

{% include 'admin/structure/footer.phtml' %}
