{% include 'admin/structure/header.phtml' %} 
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.categories.validation.js"></script>
<div id='content'>

	<form action="insert.php" method="post" id="formcategories">
		<div class="totwidth">
			<div class="panleft">
				Name:
			</div>
			<div class="panleft">
				<input type="text" id="name" name="name"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Category:
			</div>
			<div class="panleft">
				<select name="cat_id">
					{% for cat in cats %}
					<option value="{{ cat.id }}">{{ cat.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<br>
                
		<input type="submit" value="invio"/>

	</form>
</div>

{% include 'admin/structure/footer.phtml' %}
