{% include 'admin/structure/header.phtml' %}
<div id='content'>

	{% include 'admin/structure/menu.phtml' %}
	<p>
		{{ message }}
	</p>
	{% if cats|length > 0 %}
	<table class="tablelist" style='margin: 50px;'>
		<tr>
			<th>Name</th>
			<th>Category</th>
		</tr>
		{% for cat in cats %}
		<tr>
			<td><a href='show.php?id={{ cat.id }}'>{{ cat.name }}</a></td>
			<td>{{ cat.category }}</td>
			<td class="delete"><a href='delete.php?id={{ cat.id }}'>x</a></td>
			<td class="edit"><a href='prepareUpdate.php?id={{ cat.id }}'>[&#133;]</a></td>
		</tr>
		{% endfor %}
	</table>
	{%endif%}
	{% if cats|length == 0 %}
	<p>
		no elements found
	</p>
	{% endif %}
</div>

{% include 'admin/structure/footer.phtml' %}
