{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}

<div id='content'>
	<p>
		{{ message }}
	</p>
	{% if cats|length > 0 %}
	<table class="tablelist">
		<tr>
			<th>{% trans "name" %}</th>
			<th>{% trans "cat" %}</th>
		</tr>
		{% for cat in cats %}
		<tr>
			<td><a href='show.php?id={{ cat.id }}'>{{ cat.name }}</a></td>
			<td>{{ cat.category }}</td>
			<td class="delete"><a href='delete.php?id={{ cat.id }}'><img src="../../../images/icons/delete/delete-256.png" alt="Delete"></a></td>
			<td class="edit"><a href='prepareUpdate.php?id={{ cat.id }}'><img src="../../../images/icons/edit/edit-256.png" alt="Edit"></a></td>
		</tr>
		{% endfor %}
	</table>
            {% include 'admin/structure/pager.phtml' %}
	{%endif%}
	{% if cats|length == 0 %}
	<p>
		{% trans "nores" %}
	</p>
	{% endif %}
</div>

{% include 'admin/structure/footer.phtml' %}
