{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
	<table class="tablelist" style='margin: 50px;'>
		<tr>
			<th>Name</th>
			<th>Category</th>
		</tr>
		<tr>
			<td>{{ cat.name }}</td>
			<td>{{ cat.category }}</td>
			<td class="delete"><a href='delete.php?id={{ cat.id }}'>x</a></td>
			<td class="edit"><a href='prepareUpdate.php?id={{ cat.id }}'>[&#133;]</a></td>
		</tr>
	</table>
</div>
	{% include 'admin/structure/footer.phtml' %}
