<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <table border='1' style='margin: 50px;'>
            <tr>
                <td>Name</td> 
                <td>Categoy</td>
            </tr>
            <tr>
                <td>{{ cat.name }}</td> 
                <td>{{ cat.categoy }}</td>
                <td><a href=''>elimina</a></td>
                <td><a href=''>modifica</a></td>
            </tr>
        </table>
    </body>
</html>
