<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        <form action="update.php" method="post" style="padding-left: 270px;" enctype="multipart/form-data">
            <input type="hidden" name="id" value="{{ cat.id }}"/><br>
            <p>Name</p> <input type="text" name="name" value="{{ cat.name }}"/><br>

            <p>Categoy</p>

            <select name="cat_id">
                {% for category in cats %}
                <option value="{{ category.id }}" {{ category.selected }}>{{ category.name }}</option>
                {% endfor %}
            </select>

            <input type="submit" value="invio"/>

        </form>
    </body>
</html>