{% include 'header.phtml' %}
<div id='content'>
	{% include 'menu.phtml' %}
	<form action="update.php" method="post" style="padding-left: 270px;">
		<input type="hidden" name="id" value="{{ cat.id }}"/>
		<div class="totwidth">
			<div class="panleft">
				Name
			</div>
			<div class="panleft">
				<input type="text" name="name" value="{{ cat.name }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Category
			</div>

			<div class="panleft">
				<select name="cat_id">
					{% for category in cats %}
					<option value="{{ category.id }}" {{ category.selected }}>{{ category.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<br />
		<input type="submit" value="invio"/>

	</form>
</div>
{% include 'footer.phtml' %}
