{% include 'admin/structure/header.phtml' %}
<div class="login">
	<p>
		{{ message }}
	</p>
	<form method="post" action="authenticate.php">
		<p class="sign">
			{% trans "usr" %}:
		</p>
		<input class="sign" type="text" name="user"/>
		<p class="sign">
			{% trans "pwd" %}:
		</p>
		<input class="sign" type="password" name="password"/>
		<input class="invio" type="submit" value="Invio" />

	</form>
</div>
