{% include 'admin/structure/header.phtml' %}
<div class="login">
	<p class="invalid">{{ message }}</p>
	<form method="post" action="authenticate.php">
		<p class="sign">
			{% trans "usr" %} {% trans "adm" %}:
		</p>
		<input class="sign_text" type="text" name="user"/>
		<p class="sign">
			{% trans "psw" %}:
		</p>
		<input class="sign_text" type="password" name="password"/>
		<input class="invio" type="submit" value='{% trans "submit" %}' />

	</form>
</div>
