<div id="footer">
    {% set pathF = '' %}
    {% if pSession.user.id != '' and index == '' %}
        {% set pathF = '../' %}
    {% endif %}
    <div id="footer_inside">
        <ul class="footer_menu">
            <li>
                <a href="{{ pathF }}index.php">Home Page Admin Panel</a>|
            </li>
            {% if pSession.user.id != ''%}
            <li>
                <a href="{{ pathF }}logout.php">Logout</a>
            </li>
            {% endif %}
            <li>
                <a href="{{ pathF }}../change_language.php?lang=it">ITA</a>
            </li>
            <li>
                <a href="{{ pathF }}../change_language.php?lang=en">ENG</a>
            </li>
            <li>
                <a href="{{ pathF }}../change_language.php?lang=zh">CHI</a>
            </li>
        </ul>
        <br />
        <br />
        <p>
            Copyright &copy;. All rights reserved. Created by <a href="http://www.ozntone.com">OzNToNe</a>. Designed by <a href="http://www.cescoscap.it">CescoScap</a>.
        </p>

    </div>
</div>