<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    {% set path = '' %}
    {% set logInOut = 'admin' %}
    {% if pSession.user.id != '' and pSession.user.type != 'user' and pSession.user.type != 'merchant' and pSession.user.type != 'stockist' %}
        {% set logInOut = 'logout' %}
        {% if index == '' %}
            {% set path = '../' %}
        {% endif %}
    {% endif %}
    <head>
		<meta name="viewport" content="initial-scale=1, maximum-scale=1">
		<title>Mela Rossa Cash & Carry</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" type="text/css" href="{{ path }}../../content/jquery.mobile-1.3.2.min.css"/>
		<link rel="stylesheet" type="text/css" href="{{ path }}../../style/style.css"/>
		<link rel="stylesheet" type="text/css" href="{{ path }}../../content/jquery.mobile.structure-1.3.2.min.css"/>
		<link rel="stylesheet" type="text/css" href="{{ path }}../../content/jquery.mobile.theme-1.3.2.min.css"/>
		<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0-beta1.js"></script>
		<script type="text/javascript" src="{{ path }}../../scripts/jquery.mobile-1.3.2.js"></script>
		<script type="text/javascript" src="{{ path }}../../scripts/script.js"></script>
	</head>
	
	<body>
		<div data-role="page">
			<div data-role="panel" id="mypanel" data-position="right" data-display="push" style="width: 274px">

				<ul data-role="listview">
					<li data-icon="delete" data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-iconpos="right" data-theme="a" >
						<a href="#" data-rel="close" class="ui-link-inherit">Close menu</a>
					</li>

					{% if logInOut == 'logout' %}
					<li data-icon="custom" id="logout" data-theme="a">
						<!--<li data-icon="custom" id="administrator" data-theme="a">
						<a href="{{ path }}admin/login.php">{% trans "adm" %}</a>
						</li>-->
						<a href="{{ path }}{{ logInOut }}.php">{{ logInOut }}</a>
					</li>
					{% endif %}

				</ul>
			</div>
			<div data-role="header" data-position="fixed" style="height: 50px;">
				<a href="{{ path }}../index.php" data-iconpos="notext" class="ui-btn-left" data-icon="home" data-transition="flip" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="f"></a>
				<a href="#mypanel"id="login" data-icon="gear" data-iconpos="notext" class="ui-btn-right" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="f" title="Menu"></a>

			</div>
   <!-- <body>
        <div id="header_adm">
            <div id="header_inside_adm">
                <div id="redapple_adm"></div>
			 <div class="headertitle_adm">
             	 	<h1><a href="{{ path }}../../index.php">{{ company.name }}</a></h1>
            	 	<h2><a href="{{ path }}../../index.php">{{ company.description }}</a></h2>
                </div>            </div>

                <div id="topmenu_logout_adm">
                    {% if logInOut == 'logout' %}
                        <a href="{{ path }}{{ logInOut }}.php">{{ logInOut }}<img src="{{ path }}../../images/icons/system/logout/logout-256.png" alt="Logout"></a> 
                    {% endif %}
                </div>
        </div>-->
