<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
	{% set path = '' %}
	{% set logInOut = 'user' %}
	{% if pSession.user.id != '' and  pSession.user.role != 'jack' and  pSession.user.role != 'operator'%}
	{% set logInOut = 'logout' %}
	{% if index == '' %}
	{% set path = '../' %}
	{% endif %}
	{% endif %}
	<head>
		<meta name="viewport" content="initial-scale=1, maximum-scale=1">
		<title>Catalogo On Line</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" type="text/css" href="{{ path }}../../content/jquery.mobile-1.3.2.min.css"/>
		<link rel="stylesheet" type="text/css" href="{{ path }}../../style/style.css"/>
		<link rel="stylesheet" type="text/css" href="{{ path }}../../content/jquery.mobile.structure-1.3.2.min.css"/>
		<link rel="stylesheet" type="text/css" href="{{ path }}../../content/jquery.mobile.theme-1.3.2.min.css"/>
		<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0-beta1.js"></script>
		<script type="text/javascript" src="{{ path }}../../scripts/jquery.mobile-1.3.2.js"></script>
		<script type="text/javascript" src="{{ path }}../../scripts/script.js"></script>
	</head>

	<body>
		<div data-role="page" id="page">
			<div data-role="panel" id="mypanel" data-position="right" data-display="push" style="width: 274px">

				<ul data-role="listview">
					<li data-icon="delete" data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-iconpos="right" data-theme="a" >
						<a href="#" data-rel="close" class="ui-link-inherit">Close menu</a>
					</li>

					{% if logInOut == 'logout' %}
					<li data-icon="custom" id="logout" data-theme="a">
						<!--<li data-icon="custom" id="administrator" data-theme="a">
						<a href="{{ path }}admin/login.php">{% trans "adm" %}</a>
						</li>-->
						<a href="{{ path }}{{ logInOut }}.php">{{ logInOut }}</a>
					</li>
					{% endif %}
					{% set pathM = '' %}
					{% if pSession.user.id != '' and index == '' %}
					{% set pathM = '../' %}
					{% endif %}
					<li data-theme="a">
						<a href="{{ pathM }}../profile/show.php?id={{ pSession.user.id }}">{% trans "sho" %} {% trans "prof" %}</a>
					</li>
					<!--        <li>
					<a href="{{ pathM }}profile/prepareUpdate.php?id={{ pSession.user.id }}">{% trans "upd" %} {% trans "pro" %}</a>
					</li>-->
					<li data-theme="a">
						<a href="{{ pathM }}../orders/list.php">{% trans "sho" %} {% trans "ords" %}</a>
					</li>

					{% if(pSession.user.id != '' and  pSession.user.role != 'jack' and  pSession.user.role != 'operator')%}
					<li data-icon="custom" id="cart" data-theme="a">
						<a href="{{ path }}cart/list.php">{% trans "cart" %}</a>
					</li>
					{% endif %}

				</ul>
			</div>
			<div data-role="header" data-position="fixed" style="height: 50px;">
				<div class="ui-btn-left">
					<a href="{{ path }}../index.php" data-role="button" data-inline="true" data-icon="home" data-iconpos="notext"></a>
					<a data-role="button" data-inline="true" data-icon="back" data-iconpos="notext" id="back" onclick="history.back();"></a>
				</div>
				<a href="#mypanel"id="login" data-icon="gear" data-iconpos="notext" class="ui-btn-right" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="f" title="Menu"></a>

			</div>

