<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    {% set path = '' %}
    {% if pSession.user.id != '' and index == '' %}
        {% set path = '../' %}
    {% endif %}
    <head>
        <title>Mela Rossa Cash & Carry</title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
        <link rel="stylesheet" type="text/css" href="{{ path }}../../style/style.css" />
    </head>
    <body>
        <div id="header">
            <div id="header_inside">
                <img id="redapple" src="{{ path }}../../images/halfredapplep2ok.png" height="168px" width="168px"/><h1 id="headertitle">Mela Rossa Cash & Carry</h1>
                <ul id="menu">
                    <li>
                        <a href="{{ path }}../../index.php" class="but1_active">Home Page</a>
                    </li>
                    <li>
                        <a href="" class="but2">Chi siamo</a>
                    </li>
                    <li>
                        <a href="{{ path }}../../pages/where.php" class="but3">Dove siamo</a>
                    </li>
                    <li>
                        <a href="" class="but4">Contatti</a>
                    </li>
                </ul>
            </div>
        </div>
