<div id="sidebar">
    {% set pathM = '' %}
    {% if pSession.user.id != '' and index == '' %}
        {% set pathM = '../' %}
    {% endif %}
    <h2>Categorie</h2>
    <ul id="list">
        <li class="color">
            <a href="{{ pathM }}products/prepareInsert.php">Insert Product</a>
        </li>
        <li>
            <a href="{{ pathM }}products/list.php?offset=0">List all products</a>
        </li>
        <li class="color">
            <a href="{{ pathM }}categories/prepareInsert.php">Insert Category</a>
        </li>
        <li>
            <a href="{{ pathM }}categories/list.php">List all categories</a>
        </li>
        <li class="color">
            <a href="{{ pathM }}administrators/prepareInsert.php">Insert Admin</a>
        </li>
        <li>
            <a href="{{ pathM }}administrators/list.php">List all administrators</a>
        </li>
        <li class="color">
            <a href="{{ pathM }}customers/prepareInsert.php">Insert Customer</a>
        </li>
        <li>
            <a href="{{ pathM }}customers/list.php">List all customers</a>
        </li>
        <li class="color">
            <a href="{{ pathM }}orders/list.php">List all orders</a>
        </li>
        <li>
            <a href="{{ pathM }}company/list.php">Company Info</a>
        </li>   
    </ul>
</div>