<div id="sidebar">
    {% set pathM = '' %}
    {% if pSession.user.id != '' and index == '' %}
    {% set pathM = '../' %}
    {% endif %}
    <h2>Categorie</h2>
    <ul id="list">
        {% if pSession.user.role == 'jack' %}
        <li class="color">
            <a href="{{ pathM }}administrators/prepareInsert.php">Insert Admin</a>
        </li>
        <li>
            <a href="{{ pathM }}administrators/list.php">List all administrators</a>
        </li>
        <li class="color">
            <a href="{{ pathM }}company/list.php">Company Info</a>
        </li> 
        {% endif %}
        <li >
            <a href="{{ pathM }}products/prepareInsert.php">Insert Product</a>
        </li>
        <li class="color">
            <a href="{{ pathM }}products/list.php">List all products</a>
        </li>
        <li>
            <a href="{{ pathM }}categories/prepareInsert.php">Insert Category</a>
        </li>
        <li class="color">
            <a href="{{ pathM }}categories/list.php">List all categories</a>
        </li>
        <li>
            <a href="{{ pathM }}suppliers/prepareInsert.php">Insert Supplier</a>
        </li>
        <li class="color">
            <a href="{{ pathM }}suppliers/list.php">List all suppliers</a>
        </li>
        <li>
            <a href="{{ pathM }}customers/prepareInsert.php">Insert customer</a>
        </li>
        <li class="color">
            <a href="{{ pathM }}customers/list.php">List all customers</a>
        </li>
        <li>
            <a href="{{ pathM }}orders/list.php">List all orders</a>
        </li>

    </ul>
</div>