<div id="pager">
    {% if totPages > 1 %}
        <div class="pg_first">
		   <a href="list.php?offset=0">
        		<img src="../images/icon/Pager/first/first-256.png" alt="First">
	        </a>
        </div>
        {% if lr > 1 %}
            <div class="pg_prev"><a href="list.php?offset={{ lr }}">Prev</a></div>
        {%endif%}

        {% for i in range(low = lr, high = mr, step=1) %}
            {% if (i  <= totPages) and (i > 0) %}
                <div class="pg_nr"><a href="list.php?offset={{ i - 1}}">{{ i }}</a></div>
            {%endif%}
        {% endfor %}

        {% if (totPages - 1 > 6) and ((mr) < (totPages - 1))%}
            <div class="pg_next"><a href="list.php?offset={{ mr }}">Next</a></div>
        {%endif%}
        <div class="pg_last"><a href="list.php?offset={{ totPages - 1 }}">Last</a></div>
    {%endif%}
</div>