{% include 'user/structure/header.phtml' %}

<div id='content'>
    <p class="detail_adm">
        {% trans "ords" %} {% trans "list" %}
    </p>

    <p>
        {{ message }}
    </p>
    {% if orders|length > 0 %}
    <table class="tablelist">
        <tr>
            <th>{% trans "id" %}</th>
            <th>{% trans "date" %}</th>
            <th>{% trans "cust" %}</th>
        </tr>
        {% for ord in orders %}
        <tr>
            <td class="first_id"><a href='show.php?id={{ ord.id }}'>{{ ord.iden }}</a></td>
            <td>{{ ord.data }}</td>
            <td>{{ ord.client }}</td>
            {% if ord.quotation=='1' %}
            <td>{% trans 'prev' %}</td>
            {% endif %}
            {% if ord.quotation=='0' %}
            <td></td>
            {% endif %}

            <td class="delete"><a data-role="button" href='confirm.php?id={{ ord.id }}'><img
                        src="../../../images/icons/system/checkmark/checkmark-256.png" width="20%"
                        alt='{% trans "del" %}'></a></td>

            <td class="delete"><a data-role="button" href='delete.php?id={{ ord.id }}'><img
                        src="../../../images/icons/delete/delete-256.png" width="20%" alt='{% trans "del" %}'></a></td>

            <td class="delete"><a data-role="button" href='edit.php?id={{ ord.id }}'><img
                        src="../../../images/icons/edit/edit-256.png" width="20%" alt='{% trans "del" %}'></a></td>


        </tr>
        {% endfor %}
    </table>
    {% include 'user/structure/pager.phtml' %}
    {%endif%}
    {% if orders|length == 0 %}
    <p>
        {% trans "nores" %}
    </p>
    {% endif %}
</div>
{% include 'user/structure/footer.phtml' %}