{% include 'admin/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "cats" %} {% trans "list" %}
	</p>
	<p>
		{{ message }}
	</p>
	{% if cats|length > 0 %}
	<table data-role="table" data-mode="columntoggle">
		<thead>
			<th>{% trans "name" %}</th>
			<th>{% trans "cat" %}</th>
		</thead>
		<tbody>
			{% for cat in cats %}
			<tr>
				<td class="first_id"><a href='show.php?id={{ cat.id }}'>{{ cat.name }}</a></td>
				<td>{{ cat.category }}</td>
				<td class="delete"><a href='delete.php?id={{ cat.id }}'><img src="../../../images/icons/delete/delete-256.png" width="20%" alt='{% trans "del" %}'></a></td>
				<td class="edit"><a href='prepareUpdate.php?id={{ cat.id }}'><img src="../../../images/icons/edit/edit-256.png" width="20%" alt='{% trans "edit" %}'></a></td>
			</tr>
			{% endfor %}
	</table></tbody>
	{% include 'admin/structure/pager.phtml' %}
	{%endif%}
	{% if cats|length == 0 %}
	<p>
		{% trans "nores" %}
	</p>
	{% endif %}
</div>
{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}
