{% include 'admin/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "cat" %}
	</p>
	<table data-role="table" data-mode="columntoggle">
		<thead>
			<th>{% trans "name" %}</th>
			<th>{% trans "cat" %}</th>
		</thead>
		<tbody>
			<tr>
				<td>{{ cat.name }}</td>
				<td>{{ cat.category }}</td>
				<td class="delete"><a href='delete.php?id={{ cat.id }}'><img width="20%" src="../../../images/icons/delete/delete-256.png" alt='{% trans "del" %}'></a></td>
				<td class="edit"><a href='prepareUpdate.php?id={{ cat.id }}'><img width="20%" src="../../../images/icons/edit/edit-256.png" alt='{% trans "edit" %}'></a></td>
			</tr>
		</tbody>
	</table>
</div>
{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}
