{% include 'admin/structure/header.phtml' %}

<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.categories.validation.js"></script>
<div id='content'>
	<p class="detail_adm">{% trans "upd" %} {% trans "cat" %}</p>
	<form action="update.php" method="post" id="formcategories">
		<input type="hidden" name="id" value="{{ cat.id }}"/>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "name" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="name" value="{{ cat.name }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "cat" %}:
			</div>

			<div class="panleft2">
				<select name="cat_id">
					{% for category in cats %}
					<option value="{{ category.id }}" {{ category.selected }}>{{ category.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<input class="invio" type="submit" value='{% trans "submit" %}'/>

	</form>
</div>
{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}
