{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>

    {% if prods|length > 0 %}
    <table class="tablelist">
        <tr>
            <th>{% trans "name" %}</th>
            <th>{% trans "descr" %}</th>
            <th>{% trans "new" %}</th>
            <th>{% trans "ofr" %}</th>
            <th>&#128;</th>
            <th>{% trans "cod" %}</th>
            <th>{% trans "bcod" %}</th>
            <th>{% trans "sng" %} {% trans "qty" %}</th>
            <th>{% trans "pck" %} {% trans "qty" %}</th>
            <th>{% trans "cdb" %} {% trans "qty" %}</th>
            <th>{% trans "cat" %}</th>
        </tr>
        {% for prod in prods %}
        <tr>
            <td><a href='show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
            <td>{{ prod.description }}</td>
            {% if prod.new == 1 %}
                <td>Yes</td>
            {% endif %}
            {% if prod.new == 0 %}
                <td></td>
            {% endif %}
            {% if prod.offer == 1 %}
                <td>Yes</td>
            {% endif %}
            {% if prod.offer == 0 %}
                <td>x</td>
            {% endif %}
            <td>{{ prod.price }}</td>
            <td>{{ prod.cod }}</td>
            <td>{{ prod.barcode }}</td>
            <td>{{ prod.single_qty }}</td>
            <td>{{ prod.pack_qty }}</td>
            <td>{{ prod.cardboard_qty }}</td>
            <td>{{ prod.category }}</td>
            <td class="cart"><a href='../cart/add.php?id={{ prod.id }}'><img src="../../../images/icons/cart/buy/buy-256.png" alt="Add to cart"></a></td>
        </tr>
        {% endfor %}
    </table>
        {% include 'site/pager.phtml' %}

    {%endif%}
    {% if prods|length == 0 %}
    <p>
        {% trans "nores" %}
    </p>
    {% endif %}
</div>

{% include 'footer.phtml' %}