{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>

    {% if prods|length > 0 %}
    <table class="tablelist">
        <tr>
            <th>Name</th>
            <th>Descr.</th>
            <th>New</th>
            <th>Offer</th>
            <th>&#128;</th>
            <th>Cod.</th>
            <th>Barcode</th>
            <th>Single Q.ty</th>
            <th>Pack Q.ty</th>
            <th>Cardboard Q.ty</th>
            <th>Cat.</th>
        </tr>
        {% for prod in prods %}
        <tr>
            <td><a href='show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
            <td>{{ prod.description }}</td>
            {% if prod.new == 1 %}
                <td>Yes</td>
            {% endif %}
            {% if prod.new == 0 %}
                <td></td>
            {% endif %}
            {% if prod.offer == 1 %}
                <td>Yes</td>
            {% endif %}
            {% if prod.offer == 0 %}
                <td>x</td>
            {% endif %}
            <td>{{ prod.price }}</td>
            <td>{{ prod.cod }}</td>
            <td>{{ prod.barcode }}</td>
            <td>{{ prod.single_qty }}</td>
            <td>{{ prod.pack_qty }}</td>
            <td>{{ prod.cardboard_qty }}</td>
            <td>{{ prod.category }}</td>
            <td class="cart"><a href='../cart/add.php?id={{ prod.id }}'><img src="../../../images/icons/cart/buy/buy-256.png" alt="Add to cart"></a></td>
        </tr>
        {% endfor %}
    </table>
        {% include 'site/pager.phtml' %}

    {%endif%}
    {% if prods|length == 0 %}
    <p>
        no elements found
    </p>
    {% endif %}
</div>

{% include 'footer.phtml' %}