{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>
    <div class="show_product">
    		<h1>{{ prod.name }}</h1>
        <img src="../../{{ prod.image }}">
     	
     	<div class="sum_product">
     	 New:  {{ prod.new }}   
         Offer:  {{ prod.offer }}    
        {% if prod.price == prod.super_price and prod.price != prod.retail_price %}
         Orginal Price:  {{ prod.retail_price }}    
        {% endif %}
         Cod.:  {{ prod.cod }}    
         Barcode:  {{ prod.barcode }}    
         Single Q.ty:  {{ prod.single_qty }}    
         Pack Q.ty:  {{ prod.pack_qty }}    
         Cardboard Q.ty: {{ prod.cardboard_qty }}    
         Category:  {{ prod.category }}    
         Supplier:  {{ prod.supplier }}
          <h3>&#128; {{ prod.price }}</h3>    

        <div class="add_cart">
    	 		<a href='../cart/add.php?id={{ prod.id }}'><img src="../../../images/icons/cart/buy/buy-256.png" alt="Add to cart">Add to cart</a>
  	   </div>
		</div>
		<h2>{{ prod.description }}</h2>
    </div>
</div>

{% include 'footer.phtml' %}