{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>
    <div class="show_img">
        <img src="../../{{ prod.image }}">
    </div>
    <div class="show_prod">
        <ul>Name:
            <li>{{ prod.name }} </li> 
        </ul>
        <ul>Description: <li>{{ prod.description }}</li></ul> 
        <ul>New: <li>{{ prod.new }}</li></ul> 
        <ul>Offer: <li>{{ prod.offer }} </li></ul> 
        {% if prod.price == prod.super_price %}
        <ul>Orginal Price: <li>{{ prod.retail_price }} </li></ul> 
        {% endif %}
        <ul>Price: <li>{{ prod.price }} </li></ul> 
        <ul>Cod.: <li>{{ prod.cod }} </li></ul> 
        <ul>Barcode: <li>{{ prod.barcode }} </li></ul> 
        <ul>Single Qty.: <li>{{ prod.single_qty }} </li></ul> 
        <ul>Pack Qty.: <li>{{ prod.pack_qty }} </li></ul> 
        <ul>Cardboard Qty.:<li>{{ prod.cardboard_qty }} </li></ul> 
        <ul>Category: <li>{{ prod.category }} </li></ul> 
        <ul>Supplier: <li>{{ prod.supplier }} </li></ul> 
        <div class="add_cart">
    	 		<a href='../cart/add.php?id={{ prod.id }}'><img src="../../../images/icons/cart/buy/buy-256.png" alt="Add to cart">Add to cart</a>
  	   </div>

    </div>
</div>

{% include 'footer.phtml' %}