{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>
    <div class="show_product">
        <h1>{{ prod.name }}</h1>
        <img src="../../{{ prod.image }}">
        <div class="sum_product">
            {% if prod.new == 1 %}
                <img src="../../images">  
            {% endif %}
            {% if prod.offer == 1 %}
                <img src="../../images">  
            {% endif %}
            {% if prod.price == prod.super_price and prod.price != prod.retail_price %}
                Orginal Price:  {{ prod.retail_price }}    
            {% endif %}
            Cod.:  {{ prod.cod }}    
            Barcode:  {{ prod.barcode }}    
            Single Qty.:  {{ prod.single_qty }}    
            Pack Qty.:  {{ prod.pack_qty }}    
            Cardboard Qty.: {{ prod.cardboard_qty }}    
            Category:  {{ prod.category }}    
            Supplier:  {{ prod.supplier }}
            <h3>&#128; {{ prod.price }}</h3>    

            <div class="add_cart">
                <a href='../cart/add.php?id={{ prod.id }}'><img src="../../../images/icons/cart/buy/buy-256.png" alt="Add to cart">Add to cart</a>
            </div>
        </div>
        <h2>{{ prod.description }}</h2>
    </div>
</div>

{% include 'footer.phtml' %}