<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    {% set path = '' %}
    {% set logInOut = 'user' %}
    {% if pSession.user.id != '' and  pSession.user.role != 'jack' and  pSession.user.role != 'operator'%}
        {% set logInOut = 'logout' %}
        {% if index == '' %}
            {% set path = '../' %}
        {% endif %}
    {% endif %}
    <head>
        <title>Mela Rossa Cash & Carry</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" href="{{ path }}../../style/style.css" />
        <link rel="stylesheet" type="text/css" href="{{ path }}../../style/jquery-ui-1.9.2.custom.css">
        <script type="text/javascript" src="{{ path }}../../scripts/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="{{ path }}../../scripts/jquery-ui-1.9.2.custom.js"></script>
    </head>
    <body>
        <div id="header">
            <div id="header_inside">
                <div id="redapple"></div>
                <h1 id="headertitle">Mela Rossa Cash & Carry</h1>
                <ul id="menu">
                    <li>
                        <a href="{{ path }}../../index.php" class="but1_active">Home Page</a>
                    </li>
                    <li>
                        <a href="" class="but2">{% trans "who" %}</a>
                    </li>
                    <li>
                        <a href="{{ path }}../../pages/where.php" class="but3">{% trans "where" %}</a>
                    </li>
                    <li>
                        <a href="" class="but4">{% trans "contacts" %}</a>
                    </li>
                </ul>
                <div id="topmenu_logout">
                    {% if logInOut == 'logout' %}
                        <a href="{{ path }}{{ logInOut }}.php">{{ logInOut }}<img src="{{ path }}../../images/icons/system/logout/logout-256.png" alt="Logout"></a> 
                    {% endif %}
                </div>
            </div>
        </div>