<div id="sidebar">
    {% set pathM = '' %}
    {% if pSession.user.id != '' and index == '' %}
        {% set pathM = '../' %}
    {% endif %}
    <h2>Categorie</h2>
    <ul id="list">
        <li class="color">
            <a href="{{ pathM }}profile/show.php?id={{ pSession.user.id }}">Show profile</a>
        </li>
        <li>
            <a href="{{ pathM }}profile/update.php?id={{ pSession.user.id }}">Update profile</a>
        </li>
    </ul>
</div>