{% include 'admin/structure/header.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="../../../scripts/form.customers.validation.js"></script>
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<div id='content'>
	{% include 'admin/structure/menu.phtml' %}
	<form action="insert.php" method="post" style="padding-left: 270px;" id="formcustomers" enctype="multipart/form-data">
		<div class="totwidth">
			<div class="panleft">
				Name:
			</div>
			<div class="panleft">
				<input type="text" id="name" name="name"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Surname:
			</div>
			<div class="panleft">
				<input type="text" id="surname" name="surname"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Address:
			</div>
			<div class="panleft">
				<input type="text" id="address" name="address"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Email:
			</div>
			<div class="panleft">
				<input type="text" id="email" name="email"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Telephone:
			</div>
			<div class="panleft">
				<input type="text" id="telephone" name="telephone"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Cellphone:
			</div>
			<div class="panleft">
				<input type="text" id="cellphone" name="cellphone"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Active:
			</div>
			<div class="panleft">
				<input type="checkbox" name="active" />
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Password:
			</div>
			<div class="panleft">
				<input type="password" id="password" name="password"/>
			</div>
		</div>
		<br>
		
		<div class="totwidth">
			<div class="panleft">
				Operator:
			</div>
			<div class="panleft">
				<select name="adm_id">
					{% for adm in admins %}
					<option value="{{ adm.id }}">{{ adm.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
                <br>
                
                <div class="totwidth">
			<div class="panleft">
				Type:
			</div>
			<div class="panleft">
				<select name="type">
					<option value="user">user</option>
					<option value="merchant">merchant</option>
					<option value="stockist">stockist</option>
				</select>
			</div>
		</div>
		<br>
                
                <div class="totwidth">
			<div class="panleft">
				Price range:
			</div>
			<div class="panleft">
				<select name="price_range">
					<option value="1">wholesale</option>
					<option value="2">retail</option>
					<option value="3">super</option>
				</select>
			</div>
		</div>
		<br>

		<input type="submit" value="invio"/>

	</form>
</div>
{% include 'admin/structure/footer.phtml' %}
