{% include 'header.phtml' %}
<div id='content'>
	{% include 'menu.phtml' %}
	<form action="insert.php" method="post" style="padding-left: 270px;" enctype="multipart/form-data">
		<div class="totwidth">
			<div class="panleft">
				Name:
			</div>
			<div class="panleft">
				<input type="text" name="name"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Surname:
			</div>
			<div class="panleft">
				<input type="text" name="surname"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Address:
			</div>
			<div class="panleft">
				<input type="text" name="address"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Email:
			</div>
			<div class="panleft">
				<input type="text" name="email"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Telephone:
			</div>
			<div class="panleft">
				<input type="text" name="telephone"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Cellphone:
			</div>
			<div class="panleft">
				<input type="text" name="cellphone"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Active:
			</div>
			<div class="panleft">
				<input type="text" name="active"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Password:
			</div>
			<div class="panleft">
				<input type="password" name="password"/>
			</div>
		</div>
		<br>
		
		<div class="totwidth">
			<div class="panleft">
				Operator:
			</div>
			<div class="panleft">
				<select name="adm_id">
					{% for adm in admins %}
					<option value="{{ adm.id }}">{{ adm.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<br>

		<input type="submit" value="invio"/>

	</form>
</div>
{% include 'footer.phtml' %}
