{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
    <p>
        {{ message }}
    </p>
    {% if customers|length > 0 %}
    <table class="tablelist">
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Address</th>
            <th>Email</th>
            <th>Tel.</th>
            <th>Cell.</th>
            <th>Active</th>
            <th>Operator</th>
            <th>Type</th>
            <th>&#128; Range</th>
        </tr>
        {% for cus in customers %}
        <tr>
            <td><a href='show.php?id={{ cus.id }}'>{{ cus.name }}</a></td>
            <td>{{ cus.surname }}</td>
            <td>{{ cus.address }}</td>
            <td>{{ cus.email }}</td>
            <td>{{ cus.telephone }}</td>
            <td>{{ cus.cellphone }}</td>
            <td>{{ cus.active }}</td>
            <td>{{ cus.operator }}</td>
            <td>{{ cus.type }}</td>
            <td>{{ cus.price_range }}</td>
            <td class="delete"><a href='delete.php?id={{ cus.id }}'><img src="../../../images/icons/delete/delete-256.png" alt="Delete"></a></td>
            <td class="edit"><a href='prepareUpdate.php?id={{ cus.id }}'><img src="../../../images/icons/edit/edit-256.png" alt="Edit"></a></td>
        </tr>
        {% endfor %}
    </table>
        {% include 'admin/structure/pager.phtml' %}
    {%endif%}
    {% if customers|length == 0 %}
    <p>
        no elements found
    </p>
    {% endif %}
</div>
{% include 'admin/structure/footer.phtml' %}
