{% include 'admin/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "custs" %}' {% trans "list" %}
	</p>
	<p>
		{{ message }}
	</p>
	{% if customers|length > 0 %}
	<table data-role="table" data-mode="columntoggle">
		<thead>
			<th>{% trans "name" %}</th>
			<th>{% trans "sur" %}</th>
			<th>{% trans "type" %}</th>
		</thead>
		<tbody>
			{% for cus in customers %}
			<tr>
				<td class="first_id"><a href='show.php?id={{ cus.id }}'>{{ cus.name }}</a></td>
				<td>{{ cus.surname }}</td>
				<td>{{ cus.type }}</td>
				<td class="delete"><a href='delete.php?id={{ cus.id }}'><img width="50%" src="../../../images/icons/delete/delete-256.png" alt='{% trans "del" %}'></a></td>
				<td class="edit"><a href='prepareUpdate.php?id={{ cus.id }}'><img width="50%" src="../../../images/icons/edit/edit-256.png" alt='{% trans "edit" %}'></a></td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% include 'admin/structure/pager.phtml' %}
	{%endif%}
	{% if customers|length == 0 %}
	<p>
		{% trans "nores" %}
	</p>
	{% endif %}
</div>{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}
