{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
    <table class="tablelist" style='margin: 50px;'>
        <tr>
            <th>Name</th>
            <th>Surname</th>
            <th>Address</th>
            <th>Email</th>
            <th>Telephone</th>
            <th>Cellphone</th>
            <th>Active</th>
            <th>Operator</th>
            <th>Type</th>
            <th>Price Range</th>
        </tr>
        <tr>
            <td>{{ cus.name }}</td>
            <td>{{ cus.surname }}</td>
            <td>{{ cus.address }}</td>
            <td>{{ cus.email }}</td>
            <td>{{ cus.telephone }}</td>
            <td>{{ cus.cellphone }}</td>
            <td>{{ cus.active }}</td>
            <td>{{ cus.operator }}</td>
            <td>{{ cus.type }}</td>
            <td>{{ cus.price_range }}</td>
            <td class="delete"><a href='delete.php?id={{ cus.id }}'>x</a></td>
            <td class="edit"><a href='prepareUpdate.php?id={{ cus.id }}'>[&#133;]</a></td>
        </tr>
    </table>
</div>
{% include 'admin/structure/footer.phtml' %}
