{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
    <table class="tablelist">
        <tr>
            <th>Name</th>
            <th>Surname</th>
            {% if cus.cod_fis != '' %}
            <th>Cod Fiscale</th>
            {%endif%}
            {% if cus.piva != '' %}
            <th>P.IVA</th>
            {%endif%}
            <th>Address</th>
            <th>Email</th>
            <th>Tel.</th>
            <th>Cell.</th>
            <th>Active</th>
            <th>Operator</th>
            <th>Type</th>
            <th>&#128; Range</th>
        </tr>
        <tr>
            <td>{{ cus.name }}</td>
            <td>{{ cus.surname }}</td>
            {% if cus.cod_fis != '' %}
            <td>{{ cus.cod_fis }}</td>
            {%endif%}
            {% if cus.piva != '' %}
            <td>{{ cus.piva }}</td>
            {%endif%}
            <td>{{ cus.address }}</td>
            <td>{{ cus.email }}</td>
            <td>{{ cus.telephone }}</td>
            <td>{{ cus.cellphone }}</td>
            <td>{{ cus.active }}</td>
            <td>{{ cus.operator }}</td>
            <td>{{ cus.type }}</td>
            <td>{{ cus.price_range }}</td>
            <td class="delete"><a href='delete.php?id={{ cus.id }}'><img src="../../../images/icons/delete/delete-256.png" alt="Delete"></a></td>
            <td class="edit"><a href='prepareUpdate.php?id={{ cus.id }}'><img src="../../../images/icons/edit/edit-256.png" alt="Edit"></a></td>
        </tr>
    </table>
</div>
{% include 'admin/structure/footer.phtml' %}
