{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.customers.validation.js"></script>
<script type="text/javascript">
$(function (){
    if($('#type').val() === 'user'){
        $('#cf_div').show();
        $('#piva_div').hide();
    }else{
        $('#cf_div').hide();
        $('#piva_div').show();
    }
});
function toggleDivs(){
    if($('#type').val() === 'user'){
        $('#cf_div').show();
        $('#piva_div').hide();
    } else {
        $('#cf_div').hide();
        $('#piva_div').show();
    }
}
</script>
<div id='content'>
    <form action="update.php" method="post" style="padding-left: 270px;">
        <input type="hidden" name="id" value="{{ cus.id }}"/>
        <div class="totwidth">
			<div class="panleft">
				Name:
			</div>
			<div class="panleft">
				<input type="text" name="name" value="{{ cus.name }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Surname:
			</div>
			<div class="panleft">
				<input type="text" name="surname" value="{{ cus.surname }}"/>
			</div>
		</div>
		<br>
                <div class="totwidth" id="cf_div" style="display: none">
			<div class="panleft">
				Cod Fiscale:
			</div>
			<div class="panleft">
				<input type="text" id="cod_fis" name="cod_fis" value="{{ cus.cod_fis }}"/>
			</div>
		</div>
		<br>
                <div class="totwidth" id="piva_div" style="display: none">
			<div class="panleft">
				P.IVA:
			</div>
			<div class="panleft">
				<input type="text" id="piva" name="piva" value="{{ cus.piva }}"/>
			</div>
		</div>
                <br>
		<div class="totwidth">
			<div class="panleft">
				Address:
			</div>
			<div class="panleft">
				<input type="text" name="address" value="{{ cus.address }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Email:
			</div>
			<div class="panleft">
				<input type="text" name="email" value="{{ cus.email }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Telephone:
			</div>
			<div class="panleft">
				<input type="text" name="telephone" value="{{ cus.telephone }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Cellphone:
			</div>
			<div class="panleft">
				<input type="text" name="cellphone" value="{{ cus.cellphone }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Active:
			</div>
			<div class="panleft">
				<input type="checkbox" name="active" {{ cus.c_active }}/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Password:
			</div>
			<div class="panleft">
				<input type="password" name="password"/>
			</div>
		</div>
		<br>
		
		<div class="totwidth">
			<div class="panleft">
				Operator:
			</div>
			<div class="panleft">
				<select name="adm_id">
					{% for adm in admins %}
					<option value="{{ adm.id }}" {{ adm.selected }}>{{ adm.name }}</option>
					{% endfor %}
				</select>
			</div>
		</div>
		<br>
                <div class="totwidth">
			<div class="panleft">
				Type:
			</div>
			<div class="panleft">
				<select id="type" name="type" onchange="toggleDivs();">
					<option value="user" {{ cus.selected_u }}>user</option>
					<option value="merchant"  {{ cus.selected_m }}>merchant</option>
					<option value="stockist"  {{ cus.selected_s }}>stockist</option>
				</select>
			</div>
		</div>
		<br>
                <div class="totwidth">
			<div class="panleft">
				Price range:
			</div>
			<div class="panleft">
				<select name="price_range">
					<option value="1" {{ cus.selected_pw }}>wholesale</option>
					<option value="2" {{ cus.selected_pr }}>retail</option>
					<option value="3" {{ cus.selected_ps }}>super</option>
				</select>
			</div>
		</div>
		<br>
		<input type="submit" value="invio"/>

    </form>
    {% include 'admin/structure/footer.phtml' %}
