<div id="footer">
    <div id="footer_inside">
        <ul class="footer_menu">
            <li>
                <a href="index.php">Home Page</a>|
            </li>
            <li>
                <a href="pages/where.php">Dove Siamo</a>
            </li>
        </ul>
        <br />
        <br />
        <p>
            Copyright &copy;. All rights reserved. Design by Giacomo Bianchetto
        </p>

    </div>
</div>