{% set path = '' %}
{% if index == '' %}
{% set path = '../../' %}
{% endif %}

<div data-role="footer" id="footer" data-position="fixed">
	<div id="footer_inside">
		<ul style="list-style: none;">
			<li data-role="button" data-mini="true" data-inline="true">
				<a href="{{ path }}change_language.php?lang=it"><img src="{{ path }}../images/flags/italy.png" alt="ITA"></a>
			</li>
			<li data-role="button" data-mini="true" data-inline="true">
				<a href="{{ path }}change_language.php?lang=en"><img src="{{ path }}../images/flags/uk.png" alt="ENG"></a>
			</li>
			<li data-role="button" data-mini="true" data-inline="true">
				<a href="{{ path }}change_language.php?lang=zh"><img src="{{ path }}../images/flags/china.png" alt="CHI"></a>
			</li>
		</ul>
	</div>
</div>
</div>
</body>
</html>