<div id="footer">
	<div id="footer_inside">
		<ul class="footer_menu">
			<li>
				<a href="/MelaRossa/index.php">Home Page</a>|
			</li>
			<li>
				<a href="">Chi siamo</a>|
			</li>
			<li>
				<a href="/MelaRossa/pages/where.php">Dove siamo</a>|
			</li>
			<li>
				<a href="">Contatti</a>
			</li>
		</ul>
		<br />
		<br />
		<p>
			Copyright &copy;. All rights reserved. Design by Giacomo Bianchetto
		</p>

	</div>
</div>