<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
    {% set path = '' %}
    {% if index == '' %}
        {% set path = '../../' %}
    {% endif %}
    <head>
        <title>Mela Rossa Cash & Carry</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <link rel="stylesheet" type="text/css" href="{{ path }}../style/style.css" />
        <link rel="stylesheet" type="text/css" href="{{ path }}../style/jquery-ui-1.9.2.custom.css">
        <script type="text/javascript" src="{{ path }}../scripts/jquery-1.9.1.min.js"></script>
        <script type="text/javascript" src="{{ path }}../scripts/jquery-ui-1.9.2.custom.js"></script>
    </head>

    <body>
        <div id="header">
            <div id="header_inside">
                <div id="redapple"></div>
                <h1 id="headertitle"><a href="{{ path }}../../index.php">Mela Rossa Cash & Carry</a></h1>
            </div>
                <ul id="menu">
                    <li>
                        <a href="{{ path }}index.php" class="but1">Home Page</a>
                    </li>
                    <li>
                        <a href="{{ path }}who.php" class="but">{% trans "who" %}</a>
                    </li>
                    <li>
                        <a href="{{ path }}where.php" class="but">{% trans "where" %}</a>
                    </li>
                    <li>
                        <a href="{{ path }}contact_us.php" class="but">{% trans "contacts" %}</a>
                    </li>
                </ul>
                <div id="topmenu">
                	<ul>    
                            {% if not(pSession.user.id != '' and  pSession.user.role != 'jack' and  pSession.user.role != 'operator')%}
                		<li class="tpm">
                			<a href="{{ path }}user/sign_up.php">{% trans "signup" %}<img src="{{ path }}../images/icons/system/login/login-256.png" alt="Login"></a> 
                		</li>
                            {% endif %}
                		<li class="tpm">
                			<a href="{{ path }}admin/login.php">{% trans "adm" %}<img src="{{ path }}../images/icons/users/administrator/administrator-256.png" alt="Admin"></a>
                		</li>
                		<li class="tpm">
                			<a href="{{ path }}user/login.php">{% trans "user" %}<img src="{{ path }}../images/icons/users/group/group-256.png" alt="User"></a>
                		</li>
                		<li class="cart_header">
                			<a href="{{ path }}site/cart/list.php">{% trans "cart" %}<img src="{{ path }}../images/icons/cart/shopping_cart/shopping_cart-256.png" alt="Cart"></a>
                		</li>
                </div>
        </div>
