<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
	<head>
		<title>Mela Rossa Cash & Carry</title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<link rel="stylesheet" type="text/css" href="/MelaRossa/style/style.css" />
	</head>

	<body>
		<div id="header">
			<div id="header_inside">
				<img id="redapple" src="/MelaRossa/images/halfredapplep2ok.png" height="168px" width="168px"/><h1 id="headertitle">Mela Rossa Cash & Carry</h1>
				<ul id="menu">
					<li>
						<a href="/MelaRossa/index.php" class="but1_active">Home Page</a>
					</li>
					<li>
						<a href="" class="but2">Chi siamo</a>
					</li>
					<li>
						<a href="/MelaRossa/pages/where.php" class="but3">Dove siamo</a>
					</li>
					<li>
						<a href="" class="but4">Contatti</a>
					</li>
				</ul>
				<p style="float: right;padding-top: 130px;">
					<a href="">Registrazione</a> | <a href="/MelaRossa/pages/admin/login.php">Admin</a> | <a href="/MelaRossa/pages/user/login.php">User</a> | <a href="">Carrello</a>
				</p>
			</div>
		</div>
