<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
	{% set path = '' %}
	{% if index == '' %}
	{% set path = '../../' %}
	{% endif %}
	<head>
		<meta name="viewport" content="initial-scale=1, maximum-scale=1">
		<title>Catalogo On Line</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<link rel="stylesheet" type="text/css" href="{{ path }}../content/jquery.mobile-1.3.2.min.css"/>
		<link rel="stylesheet" type="text/css" href="{{ path }}../style/style.css"/>
		<link rel="stylesheet" type="text/css" href="{{ path }}../content/jquery.mobile.structure-1.3.2.min.css"/>
		<link rel="stylesheet" type="text/css" href="{{ path }}../content/jquery.mobile.theme-1.3.2.min.css"/>
		<script type="text/javascript" src="//code.jquery.com/jquery-1.11.0-beta1.js"></script>
		<script type="text/javascript" src="{{ path }}../scripts/jquery.mobile-1.3.2.js"></script>
		<script type="text/javascript" src="{{ path }}../scripts/script.js"></script>

	</head>
	<body>
		<div data-role="page">
			<div data-role="header" data-position="fixed" style="height: 50px;">
				<a href="{{ path }}index.php" data-iconpos="notext" class="ui-btn-left" data-icon="home" data-transition="flip" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="f"></a>
				<a href="#mypanel"id="login" data-icon="gear" data-iconpos="notext" class="ui-btn-right" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="f" title="Menu"></a>

			</div>
