{% include 'header.phtml' %}
{% include 'menu.phtml' %}
{% include 'menu-right.phtml' %}
<link rel="stylesheet" type="text/css" href="../style/jquery.bxslider.css"/>
<script type="text/javascript" src="../scripts/jquery.bxslider.min.js"></script>

<script type="text/javascript">
    $(function() {
        $('#slider1').bxSlider({
            auto: true,
            autoControls: true,
            pause: 5000,
            captions: true
        });
    });
</script>
<div id="content">
    <div id="sliderContainer">
        <ul id="slider1">
            {% for prod in prods %}
            <li><img src="{{ prod.image }}" alt="{{ prod.tile }}" title="{{ prod.tile }}"/></li>
            {% endfor %}
        </ul>
    </div>
</div>
{% include 'footer.phtml' %}


