{% include 'header.phtml' %}
{% include 'menu.phtml' %}
{% include 'menu-right.phtml' %}



<!--<a href="#categoriespanel" id="login" data-role="button" data-icon="plus"
data-iconpos="left" class="ui-btn-right" data-corners="true"
data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-theme="a"
style="text-decoration: none">Categorie</a>-->

<a href="{{ path }}user/login.php" data-role="button" data-icon="custom" id="user" data-theme="a">Login {% trans "user" %}</a>
{% include 'footer.phtml' %}

