{% set path = '' %}
{% if index == '' %}
{% set path = '../../' %}
{% endif %}
<!--<link rel='stylesheet' type='text/css' href='{{ path }}../style/accordion.css' />-->

<div data-role="panel" id="categoriespanel" data-position="left" data-display="push">

	<div id="menujs" onload="categoryload()" >
		<div data-role="collapsible" data-collapsed="true" data-theme="a" id="collapsetest" style="padding: 0; margin: 0;">
			<h3>Offerte/Novità</h3>
			<a data-role="button" data-icon="arrow-r" data-iconpos="right" href="{{ path }}site/products/list_tag.php?tag=new">{% trans "new" %}</a>
			<a data-role="button" data-icon="arrow-r" data-iconpos="right" href="{{ path }}site/products/list_tag.php?tag=offer">{% trans "ofr" %}</a>
		</div>
		<ul data-role="lisview" id="listcat">

		</ul>
	</div>
</div>

<script type="text/javascript">
	//    link per cats '{{ path }}site/products/list.php?id_cat=' + id
	$(document.getElementById('menujs')).ready(function() {

		$.post("{{ path }}menu.php", function(data) {
			$('#listcat').empty();
			for (var i = 0; i < data.length; i++) {

				$('#listcat').append('<li><a href="{{ path }}/catalogoonline/pages/site/products/list.php?id_cat=' + data[i]['id'] + '">' + data[i]['name'] + '</a></li>');
				for (var j = 0; j < data[i]['category'].length; j++) {
					$('#listcat').append('<li><a href="{{ path }}/catalogoonline/pages/site/products/list.php?id_cat=' + data[i]['category'][j]['id'] + '">' + data[i]['category'][j]['name'] + '</a></li>');
					for (var k = 0; k < data[i]['category'][j]['category'].length; k++) {
						$('#listcat').append('<li><a href="{{ path }}/catalogoonline/pages/site/products/list.php?id_cat=' + data[i]['category'][j]['category'][k]['id'] + '">' + data[i]['category'][j]['category'][k]['name'] + '</a></li>');
						$('#listcat').listview().listview('refresh');
					}
				}
			}

		}, "json");
		document.cookie = "precurl=" + document.URL;
	});

</script>