<div data-role="panel" id="mypanel" data-position="right" data-display="overlay">

	<ul data-role="listview">
		<li data-icon="delete" data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-iconpos="right" data-theme="a" >
			<a href="#" data-rel="close" class="ui-link-inherit">Close menu</a>
		</li>
		{% if not(pSession.user.id != '' and  pSession.user.role != 'jack' and  pSession.user.role != 'operator')%}
		<li data-icon="custom" id="signup" data-theme="a">
			<a href="{{ path }}user/sign_up.php">{% trans "signup" %}</a>
		</li>
		{% endif %}
		<li data-icon="custom" id="user" data-theme="a">
			<a href="{{ path }}login.php">{% trans "signin" %}</a>
		</li>
		{% if(pSession.user.id != '' and  pSession.user.role != 'jack' and  pSession.user.role != 'operator')%}
		<li data-icon="custom" id="cart" data-theme="a">
			<a href="{{ path }}site/cart/list.php">{% trans "cart" %}</a>
		</li>
		{% endif %}
	</ul>
</div>