{% set path = '' %}
{% if index == '' %}
{% set path = '../../' %}
{% endif %}
<script type="text/javascript">
    $.post("{{ path }}menu-right.php",
            function(data) {
                if (data.length == 0) {
                    $('#slider2').append("<p>No result found.</p>");
                } else {
                    var a, li, img, ul;
                    for (var i = 0; i < data.length; i++) {
                        img = document.createElement('img');
                        img.setAttribute("src", data[i]["image"]);
                        img.setAttribute("alt", data[i]["name"]);
                        img.setAttribute("title", data[i]["name"]+" "+data[i]["price"]);
                        
                        a = document.createElement('a');
                        a.setAttribute('href', 'site/products/show.php?id=' + data[i]['id']);
                        a.appendChild(img);
                        
                        li = document.createElement('li');
                        li.appendChild(a);
                        
                        $('#slider2').append(li);
                    }
                }
                 $('#slider2').bxSlider({
                        mode: 'vertical',
                        auto: true,
                        autoControls: true,
                        pause: 5000,
                        captions: true
                    });
            }, "json");

</script>
<div class="menu-right"> 
    <div id="sliderContainer2">
        <ul id="slider2">
            
        </ul>
    </div>
</div>
