{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>
    
    {% if prods|length > 0 %}
    <table class="tablelist">
        <tr>
            <th>Name</th>
            <th>Descr.</th>
            <th>&#128;</th>
            <th>Cod.</th>
            <th>Cat.</th>
            <th>Q.ty</th>
        </tr>
        {% for prod in prods %}
        <tr>
            <td><a href='../products/show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
            <td>{{ prod.description }}</td>
            <td>{{ prod.price }}</td>
            <td>{{ prod.cod }}</td>
            <td>{{ prod.category }}</td>
            <td>{{ prod.qty }}</td>
            <td class="remove_cart"><a href='remove.php?id={{ prod.id }}'><img src="../../../images/icons/cart/return/return-256.png" alt="Remove"></a></td>
        </tr>
        {% endfor %}
        <tr>Total: {{ tot }}</tr>
    </table>
    <div class="empty_cart">
    	  <a href='empty.php'><img src="../../../images/icons/delete/delete-256.png" alt="Delete">Empty cart</a>
    </div>
    {%endif%}
    {% if prods|length == 0 %}
    <p>
        your cart is empty.
    </p>
    {% endif %}
</div>

{% include 'footer.phtml' %}