{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>

    {% if prods|length > 0 %}
    <table class="tablelist">
        <tr>
            <th>Name</th>
            <th>Descr.</th>
            <th>&#128;</th>
            <th>Cod.</th>
            <th>Cat.</th>
            <th>Q.ty</th>
        </tr>
        {% for prod in prods %}
        <tr>
            <td><a href='../products/show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
            <td>{{ prod.description }}</td>
            <td>{{ prod.price }}</td>
            <td>{{ prod.cod }}</td>
            <td>{{ prod.category }}</td>
            <td class="td_qty">
                <form action="update.php" method="post">
                    <input type="hidden" name="id" value="{{ prod.id }}"/>
                    <input type="text" id="qty_add" name="qty_add" value="{{ prod.qty }}"/>
                    <input type="submit"/>
                </form>
            </td>
            <td class="remove_cart"><a href='remove.php?id={{ prod.id }}'><img src="../../../images/icons/cart/return/return-256.png" alt="Remove"></a></td>
        </tr>
        {% endfor %}
    </table>
    <ul>
        <li class="total">
            <img src="../../../images/icons/cart/shopping_cart_filled/shopping_cart_filled-256.png" alt="Total">Total:  <b>&#128;{{ tot }}</b>
        </li>
        <li class="checkout">
            <a href='../order/summary.php'><img src="../../../images/icons/cart/checkout/checkout_green-256.png" alt="Checkout">Checkout</a>
        </li>
        <li class="empty_cart">
            <a href='empty.php'><img src="../../../images/icons/cart/return/return_red-256.png" alt="Delete">Empty cart</a>
        </li>
    </ul>
    {% if back != '' %}
    <div class="back">
            <a href='{{ back }}'><img src="../../../images/icons/list/list-256.png" alt="Back"><img src="../../../images/icons/arrows/left/left-256.png" alt="Back"></a>
    </div>
    {%endif%}
    {%endif%}
    {% if prods|length == 0 %}
    <p>
        Your cart is empty.
    </p>
    {% endif %}
</div>

{% include 'footer.phtml' %}