{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>
    
    {% if prods|length > 0 %}
    <a href='empty.php'><img src="../../../images/icons/delete/delete-256.png" alt="Delete"> empty cart</a>
    <table class="tablelist">
        <tr>
            <th>Name</th>
            <th>Descr</th>
            <th>Price</th>
            <th>Cod</th>
            <th>Category</th>
            <th>Qty</th>
        </tr>
        {% for prod in prods %}
        <tr>
            <td><a href='../products/show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
            <td>{{ prod.description }}</td>
            <td>{{ prod.price }}</td>
            <td>{{ prod.cod }}</td>
            <td>{{ prod.category }}</td>
            <td>{{ prod.qty }}</td>
            <td class="edit"><a href='remove.php?id={{ prod.id }}'><img src="../../../images/icons/delete/delete-256.png" alt="Remove"></a></td>
        </tr>
        {% endfor %}
        <tr>{{ tot }}</tr>
    </table>
    {%endif%}
    {% if prods|length == 0 %}
    <p>
        your cart is empty.
    </p>
    {% endif %}
</div>

{% include 'footer.phtml' %}