{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>
    
    {% if prods|length > 0 %}
    <a href='removeFormCart.php?id={{ prod.id }}'><img src="../images/icons/Adds/delete/delete-256.png" alt="Delete"></a>
    <table class="tablelist">
        <tr>
            <th>Name</th>
            <th>Descr</th>
            <th>Price</th>
            <th>Cod</th>
            <th>Category</th>
            <th>Qty</th>
        </tr>
        {% for prod in prods %}
        <tr>
            <td><a href='product_show.php?id={{ prod.id }}'>{{ prod.name }}</a></td>
            <td>{{ prod.description }}</td>
            <td>{{ prod.price }}</td>
            <td>{{ prod.cod }}</td>
            <td>{{ prod.category }}</td>
            <td>{{ prod.qty }}</td>
            <td class="edit"><a href='removeFormCart.php?id={{ prod.id }}'><img src="../images/icons/Adds/add_list/add_list-256.png" alt="Remove"></a></td>
        </tr>
        {% endfor %}
    </table>
        {% include 'site/pager.phtml' %}

    {%endif%}
    {% if prods|length == 0 %}
    <p>
        no elements found
    </p>
    {% endif %}
</div>

{% include 'footer.phtml' %}