{% include 'user/structure/header.phtml' %}

<div id='content'>
    <p class="detail_adm">
        {% trans "custs" %} {% trans "list" %}
    </p>

    <p>
        {{ message }}
    </p>

    {% if custs|length > 0 %}
    <table data-role="table" data-mode="columntoggle">
        <thead>
        <th>
           {% trans "name" %}
        </th>
        </thead>
        <tbody>
        {% for cust in custs %}
        <tr>
            <td class="first_id"><a data-role="button" data-inline="true" href='../clients/show.php?id={{ cust.id }}'>{{cust.name}}</a>
            </td>
            <td class="first_id"><a data-role="button" data-inline="true"
                                    href='../orders/orderByClient.php?id={{ cust.id }}'>{%trans "sho"%} {%trans
                    "ords"%}</a></td>
            <td class="first_id"><a data-role="button" data-inline="true"
                                    href='../quotation/quotationByClient.php?id={{ cust.id }}'>{%trans "sho"%} {%trans
                    "prevs"%}</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include 'user/structure/pager.phtml' %}
    {%endif%}
    {% if custs|length == 0 %}
    <p>
        {% trans "nores" %}
    </p>
    {% endif %}
</div>
{% include 'user/structure/footer.phtml' %}