{% include 'header.phtml' %}
{% include 'menu.phtml' %}
<div id='content'>
	{% if prods|length > 0 %}
	<table class="tablelist">
		<tr>
			<th>{% trans "name" %}</th>
			<th>{% trans "descr" %}</th>
			<th>&#128;</th>
			<th>{% trans "cod" %}</th>
			<th>{% trans "qty" %}</th>
		</tr>
		{% for prod in prods %}
		<tr>
			<td><a href='../products/show.php?id={{ prod.id }}'>{{ prod.name }}</a></td><!-- lasciare visualizzazione?? -->
			<td>{{ prod.description }}</td>
			<td><b>{{ prod.price }}</b></td>
			<td><i>{{ prod.cod }}</i></td>
			<td style="text-align:center">{{ prod.qty }}</td>
		</tr>
		{% endfor %}
	</table>
	<ul class="listnone">
		<form action="confirm.php" method="post">
			{% if addrs|length == 0 %}
			<li>
				<button type="submit" value="{% trans "confirm" %}" class="confirm" >
					<img src="../../../images/icons/cart/checkout/checkout_green-256.png" alt='{% trans "confirm" %}'>{% trans "confirm" %}
				</button>
			</li>
			{% endif %}
			{% if addrs|length !=0 %}
			<li>
				{% trans "adr" %}
				<select name="a_id">
					{% for addr in addrs %}
					<option value="{{ addr.id }}">{{ addr.street }}</option>
					{% endfor %}
				</select>
			</li>
			<li>
				<button type="submit" value="{% trans "confirm" %}" class="confirm" >
					<img src="../../../images/icons/cart/checkout/checkout_green-256.png" alt='{% trans "confirm" %}'>{% trans "confirm" %}
				</button>
			</li>
			
			{% endif %}

			<li class="empty_cart">
				<a href='../cart/empty.php'><img src="../../../images/icons/cart/return/return_red-256.png" alt='{% trans "canc" %} {% trans "ord" %}'>{% trans "canc" %} {% trans "ord" %}</a>
			</li>
		</form>
	</ul>
	{%endif%}
	{% if prods|length == 0 %}
	<p>
		{% trans "usr.emp.cart" %}
	</p>
	{% endif %}
</div>

{% include 'footer.phtml' %}