{% include 'header.phtml' %}
<div id='content'>
    {% if prods|length > 0 %}
    <table class="tablelist">
        <tr>
            <th>{% trans "name" %}</th>
            <th>{% trans "descr" %}</th>
            <th>&#128;</th>
            <th>{% trans "cod" %}</th>
            <th>{% trans "qty" %}</th>
        </tr>
        {% for prod in prods %}
        <tr>
            <td><a href='../products/show.php?id={{ prod.id }}'>{{ prod.name }}</a></td> <!-- lasciare visualizzazione?? -->
            <td>{{ prod.description }}</td>
            <td><b>{{ prod.price }}</b></td>
            <td><i>{{ prod.cod }}</i></td>
            <td style="text-align:center">{{ prod.qty }}</td>
        </tr>
        {% endfor %}
    </table>
    <ul>
        {% if addrs != '' %}
        <li class="checkout">
            <a href='#'><img src="../../../images/icons/cart/checkout/checkout_green-256.png" alt='{% trans "confirm" %}'>{% trans "confirm" %}</a>
            <form action="confirm.php" method="post">
                {% trans "adr" %}
                <select name="a_id">
                    {% for addr in addrs %}
                    <option value="{{ addr.id }}">{{ addr.street }}</option>
                    {% endfor %}
                </select>
                <input type="submit" value='{% trans "confirm" %}'/>
            </form>
            <form>
            </form>

        </li>
        {% endif %}
        {% if addrs == '' %}
            <li class="checkout">
                <a href='confirm.php'><img src="../../../images/icons/cart/checkout/checkout_green-256.png" alt='{% trans "confirm" %}'>{% trans "confirm" %}</a>
            </li>
        {% endif %}

        <li class="empty_cart">
            <a href='../cart/empty.php'><img src="../../../images/icons/cart/return/return_red-256.png" alt='{% trans "canc" %} {% trans "ord" %}'>{% trans "canc" %} {% trans "ord" %}</a>
        </li>
    </ul>
    {%endif%}
    {% if prods|length == 0 %}
    <p>
        {% trans "usr.emp.cart" %}
    </p>
    {% endif %}
</div>

{% include 'footer.phtml' %}