{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.suppliers.validation.js"></script>
<div id='content'>
	<form action="insert.php" id="formsuppliers" method="post" >
		<div class="totwidth">
			<div class="panleft1">
				Name
			</div>
			<div class="panleft2">
				<input type="text" name="name" />
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft1">
				Description
			</div>
			<div class="panleft2">
				<input type="text" name="description" />
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft1">
				P. IVA
			</div>
			<div class="panleft2">
				<input type="text" name="piva" />
			</div>
		</div>
		<br>
                <div class="totwidth">
			<div class="panleft1">
				Telephone
			</div>
			<div class="panleft2">
				<input type="text" name="telephone" />
			</div>
		</div>
		<br>
                <div class="totwidth">
			<div class="panleft1">
				Fax
			</div>
			<div class="panleft2">
				<input type="text" name="fax" />
			</div>
		</div>
		<br>
                <div class="totwidth">
			<div class="panleft1">
				Address
			</div>
			<div class="panleft2">
				<input type="text" name="address" />
			</div>
		</div>
		<br>

		<input class="invio" type="submit" value="Invio"/>

	</form>
</div>
{% include 'admin/structure/footer.phtml' %}
