{% include 'admin/structure/header.phtml' %}

<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.suppliers.validation.js"></script>
<div id='content'>
	<p class="detail_adm">{% trans "ins" %} {% trans "sup" %}</p>
	<form action="insert.php" id="formsuppliers" method="post" >
		<div class="totwidth">
			<div class="panleft1">
				{% trans "name" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="name" />
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "descr" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="description" />
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "piva" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="piva" />
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "mail" %}:
			</div>
			<div class="panleft2">
				<input type="text" id="email" name="email"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "tel" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="telephone" />
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "fax" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="fax" />
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "adr" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="address" />
			</div>
		</div>
		<input class="invio" type="submit" value='{% trans "submit" %}'/>

	</form>
</div>{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}
