{% include 'admin/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">
		{% trans "sups" %} {% trans "list" %}
	</p>
	<p>
		{{ message }}
	</p>
	{% if suppliers|length > 0 %}
	<table data-role="table"  data-mode="columntoggle">
		<thead>
			<th>{% trans "name" %}</th>
			<th>{% trans "descr" %}</th>

			<th>{% trans "tel" %}</th>

		</thead>
		<tbody>
			{% for d in suppliers %}
			<tr>
				<td class="first_id"><a href='show.php?id={{ d.id }}'>{{ d.name }}</a></td>
				<td>{{ d.description }}</td>

				<td>{{ d.telephone }}</td>

			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% include 'admin/structure/pager.phtml' %}
	{% endif %}
	{% if suppliers|length == 0 %}
	<p>
		{% trans "nores" %}
	</p>
	{% endif %}
</div>
{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}