{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
    <p>
        {{ message }}
    </p>
    {% if suppliers|length > 0 %}
    <table class="tablelist">
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>P. IVA</th>
            <th>Tel.</th>
            <th>Fax</th>
            <th>Address</th>

        </tr>
        {% for d in suppliers %}
        <tr>
            <td><a href='show.php?id={{ d.id }}'>{{ d.name }}</a></td>
            <td>{{ d.description }}</td>
            <td>{{ d.piva }}</td>
            <td>{{ d.telephone }}</td>
            <td>{{ d.fax }}</td>
            <td>{{ d.address }}</td>
            <td class="delete"><a href='delete.php?id={{ d.id }}'><img src="../../../images/icons/delete/delete-256.png" alt="Delete"></a></td>
            <td class="edit"><a href='prepareUpdate.php?id={{ d.id }}'><img src="../../../images/icons/edit/edit-256.png" alt="Edit"></a></td>
        </tr>
        {% endfor %}
    </table>
        {% include 'admin/structure/pager.phtml' %}
    {% endif %}
    {% if suppliers|length == 0 %}
    <p>
        {% trans "nores" %}
    </p>
    {% endif %}
</div>

{% include 'admin/structure/footer.phtml' %}