{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
    <table class="tablelist" style='margin: 50px;'>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>P. IVA</th>
            <th>Telephone</th>
            <th>Fax</th>
            <th>Address</th>

        </tr>
        <tr>
            <td>{{ supplier.name }}</td>
            <td>{{ supplier.description }}</td>
            <td>{{ supplier.piva }}</td>
            <td>{{ supplier.telephone }}</td>
            <td>{{ supplier.fax }}</td>
            <td>{{ supplier.address }}</td>
        </tr>
    </table>
</div>
{% include 'admin/structure/footer.phtml' %}
