{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<div id='content'>
    <table class="tablelist">
        <tr>
            <th>{% trans "name" %}</th>
            <th>{% trans "descr" %}</th>
            <th>{% trans "piva" %}</th>
            <th>{% trans "tel" %}</th>
            <th>{% trans "fax" %}</th>
            <th>{% trans "adr" %}</th>
        </tr>
        <tr>
            <td>{{ supplier.name }}</td>
            <td>{{ supplier.description }}</td>
            <td>{{ supplier.piva }}</td>
            <td>{{ supplier.telephone }}</td>
            <td>{{ supplier.fax }}</td>
            <td>{{ supplier.address }}</td>
            <td class="delete"><a href='delete.php?id={{ cus.id }}'><img src="../../../images/icons/delete/delete-256.png" alt="Delete"></a></td>
            <td class="edit"><a href='prepareUpdate.php?id={{ cus.id }}'><img src="../../../images/icons/edit/edit-256.png" alt="Edit"></a></td>
        </tr>
    </table>
</div>
{% include 'admin/structure/footer.phtml' %}
