{% include 'admin/structure/header.phtml' %}

<div id='content'>
	<p class="detail_adm">{% trans "sup" %}</p>
 
            <p>{% trans "name" %}: {{ supplier.name }}</p>
            <p>{% trans "descr" %}: {{ supplier.description }}</p>
            <p>{% trans "piva" %}: {{ supplier.piva }}</p>
            <p>{% trans "mail" %}: {{ supplier.email }}</p>
            <p>{% trans "tel" %}: {{ supplier.telephone }}</p>
            <p>{% trans "fax" %}: {{ supplier.fax }}</p>
            <p>{% trans "adr" %}: {{ supplier.address }}</p>
            <a data-role="button" href='delete.php?id={{ cus.id }}'><img src="../../../images/icons/delete/delete-256.png" height="50px" alt='{% trans "del" %}'></a>
            <a data-role="button" href='prepareUpdate.php?id={{ cus.id }}'><img src="../../../images/icons/edit/edit-256.png" height="50px" alt='{% trans "edit" %}'></a>
  
</div>{% include 'admin/structure/menu.phtml' %}
{% include 'admin/structure/footer.phtml' %}
