{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.suppliers.validation.js"></script>
<div id='content'>
	<p class="detail_adm">{% trans "upd" %} {% trans "sup" %}</p>
	<form action="update.php" method="post" id="formsuppliers">
		<input type="hidden" name="id" value="{{ supplier.id }}"/>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "name" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="name" value="{{ supplier.name }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "descr" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="description" value="{{ supplier.description }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "piva" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="piva" value="{{ supplier.piva }}"/>
			</div>
		</div>
		<div class="totwidth">
			<div class="panleft1">
				{% trans "mail" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="email" value="{{ supplier.email }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "tel" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="telephone" value="{{ supplier.telephone }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "fax" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="fax" value="{{ supplier.fax }}"/>
			</div>
		</div>
                <div class="totwidth">
			<div class="panleft1">
				{% trans "adr" %}:
			</div>
			<div class="panleft2">
				<input type="text" name="address" value="{{ supplier.address }}"/>
			</div>
		</div>
		<input class="invio" type="submit" value='{% trans "submit" %}'/>

	</form>
</div>
{% include 'admin/structure/footer.phtml' %}
