{% include 'admin/structure/header.phtml' %}
{% include 'admin/structure/menu.phtml' %}
<script type="text/javascript" src="../../../scripts/jquery.validate.js"></script>
<script type="text/javascript" src="../../../scripts/validation/admin/form.suppliers.validation.js"></script>
<div id='content'>
	<form action="update.php" method="post" id="formsuppliers">
		<input type="hidden" name="id" value="{{ supplier.id }}"/>
		<div class="totwidth">
			<div class="panleft">
				Name
			</div>
			<div class="panleft">
				<input type="text" name="name" value="{{ supplier.name }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				Description
			</div>
			<div class="panleft">
				<input type="text" name="description" value="{{ supplier.description }}"/>
			</div>
		</div>
		<br>
		<div class="totwidth">
			<div class="panleft">
				P. IVA
			</div>
			<div class="panleft">
				<input type="text" name="piva" value="{{ supplier.piva }}"/>
			</div>
		</div>
		<br>
                <div class="totwidth">
			<div class="panleft">
				Telephone
			</div>
			<div class="panleft">
				<input type="text" name="telephone" value="{{ supplier.telephone }}"/>
			</div>
		</div>
		<br>
                <div class="totwidth">
			<div class="panleft">
				Fax
			</div>
			<div class="panleft">
				<input type="text" name="fax" value="{{ supplier.fax }}"/>
			</div>
		</div>
		<br>
                <div class="totwidth">
			<div class="panleft">
				Address
			</div>
			<div class="panleft">
				<input type="text" name="address" value="{{ supplier.address }}"/>
			</div>
		</div>
		<br>

		<input type="submit" value="invio"/>

	</form>
</div>
{% include 'admin/structure/footer.phtml' %}
