{% include 'user/structure/header.phtml' %}
{% include 'user/products/productBar.phtml' %}
<div id='content'>
    <div class="list_products">
        <div class="list_products_nav">
            {% for cat in oCats %}
            <a href="list.php?id_cat={{ cat.id }}">{{ cat.name }}</a>&nbsp;|
            {% endfor %}
        </div>
        <ul data-role="listview">
            {% for prod in prods %}
            <li>
                <a href='show.php?id={{ prod.id }}'>
                    <div class="list_products_inner">

                        <h1>{{ prod.name }}</h1>

                        <h2>&#128; {{ prod.retail_price }}</h2>

                        {% if prod.new == 1 %}
                        <p class="new_badge">
                            {% trans "new" %}

                        <p>
                            {% endif %}
                            {% if prod.offer == 1 %}

                        <p class="offer_badge">
                            {% trans "ofr" %}

                        <p>
                            {% endif %}
                    </div>
                    <img src="../../{{ prod.image }}"/> </a>
            </li>
            {% endfor %}
        </ul>
        <div class="pre_pager"></div>
        <div id="pager">
            {% if totPages > 1 %}
            <div class="pg_first" style="float: left; padding-left: 20px;">
                <a href="list.php?catl={{ catl }}&catego={{ catego }}">
                    <img src="../../../images/icons/Pager/first/first-256.png" height="50px" alt="First">
                </a>
            </div>
            {% if lr > 1 %}
            <div class="pg_prev">
                <a href="list.php?offset={{ lr }}&catl={{ catl }}&catego={{ catego }}"
                   style="float: left; padding-left: 20px;">
                    <img src="../../../images/icons/Pager/previous/previous-256.png" height="50px" alt="Previous">
                </a>
            </div>
            {%endif%}

            {% for i in range(low = lr, high = mr, step=1) %}
            {% if (i <= totPages) and (i > 0) %}
            <div class="pg_nr" style="float: left; padding-left: 20px;">
                <a href="list.php?offset={{ i - 1}}&catl={{ catl }}&catego={{ catego }}">
                    {{ i }}
                </a>
            </div>
            {%endif%}
            {% endfor %}

            {% if (totPages - 1 > 6) and ((mr) < (totPages - 1))%}
            <div class="pg_next" style="float: left; padding-left: 20px;">
                <a href="list.php?offset={{ mr }}&catl={{ catl }}&catego={{ catego }}">
                    <img src="../../../images/icons/Pager/next/next-256.png" height="50px" alt="Next">
                </a>
            </div>
            {%endif%}
            <div class="pg_last" style="float: left; padding-left: 20px;">
                <a href="list.php?offset={{ totPages - 1 }}&catl={{ catl }}&catego={{ catego }}">
                    <img src="../../../images/icons/Pager/last/last-256.png" height="50px" alt="Last">
                </a>
            </div>
            {%endif%}
        </div>
    </div>
</div>

{% include 'user/structure/footer.phtml' %}