{% include 'user/structure/header.phtml' %}
{% include 'user/products/productBar.phtml' %}
<div id='content'>
    <div class="list_products">
        <div class="list_products_nav">
            {% for cat in oCats %}
            <a href="list.php?id_cat={{ cat.id }}">{{ cat.name }}</a>&nbsp;|
            {% endfor %}
        </div>
        <ul data-role="listview" data-filter="true">
            {% for prod in prods %}
            <li>
                <a href='show.php?id={{ prod.id }}'>
                    <div class="list_products_inner">

                        <h1>{{ prod.name }}</h1>

                        <h2>&#128; {{ prod.retail_price }}</h2>

                        {% if prod.new == 1 %}
                        <p class="new_badge">
                            {% trans "new" %}

                        <p>
                            {% endif %}
                            {% if prod.offer == 1 %}

                        <p class="offer_badge">
                            {% trans "ofr" %}

                        <p>
                            {% endif %}
                    </div>
                    <img src="../../{{ prod.image }}"/> </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>

{% include 'user/structure/footer.phtml' %}