<div data-role="navbar" data-iconpos="top">
    <ul>
        <li><a href="prepareListByCode.php" data-icon="search">{% trans "search" %} {% trans "by" %} {% trans "cod"
                %}</a></li>
        <li><a href="listComplete.php" data-icon="search">{% trans "search.from.complete.list" %}</a></li>
        <li><a href="prepareListByDN.php" data-icon="search">{% trans "search" %} {% trans "by" %} {% trans "name" %}/{%
                trans "descr" %}</a></li>
    </ul>
</div>