{% include 'header.phtml' %}
{% include 'menu.phtml' %}
{% include 'menu-right.phtml' %}
<div id='content'>

	{% if prod.new == 1 %}
	<p >
		{% trans "new" %}
	<p>
		{% endif %}
		{% if prod.offer == 1 %}
	<p class="offer_badge">
		{% trans "ofr" %}
	<p>
		{% endif %}

		<!--		  {% if prod.new == 1 %}
		<img class="new" src="../../../images/icons/new/new-512.png">
		{% endif %}
		{% if prod.offer == 1 %}
		<img class="sale" src="../../../images/icons/sale/sale-512.png">
		{% endif %}
		-->

		<h1>{{ prod.name }}</h1>
		<h6>{% trans "by" %} <i><b>{{ prod.supplier }}</b></i></h6>

		<h7>
			{% trans "cat" %}: <b>{{ prod.category }}</b>
		</h7>
		<img src="../../{{ prod.image }}" width="100%">
		<h4>{{ prod.barcode }}</h4>

		<ul>
			<li >
				{% trans "cod" %}:  #<b>{{ prod.cod }}</b>
			</li>
			<li >
				{% trans "qty" %}:
			<li >
				{% trans "sng" %}: <b>{{ prod.single_qty }}</b>
			</li>
			<li >
				{% trans "pck" %}: <b>{{ prod.pack_qty }}</b>
			</li>
			<li >
				{% trans "cdb" %}: <b>{{ prod.cardboard_qty }}</b>
			</li>
			</li>
		</ul>
		<br>
		<h5> {% if prod.price == prod.super_price and prod.price != prod.retail_price %}
		&#128; {{ prod.retail_price }}
		{% endif %} </h5>
		<h3> &#128; {{ prod.price }} </h3>

		<div >
			<span>{% trans "sel" %} {% trans "qty" %}:
				<input type="text" id="qty_add" name="qty_add" value="1"/>
			</span>
		</div>
		<form action="../cart/add.php" method="post">
			<input type="hidden" name="id" value="{{ prod.id }}"/>
			<button type="submit" id="addcart" value='{% trans "submit" %}' data-icon="custom">
				{% trans "add.cart" %}
			</button>
		</form>

		<br>
		<h2>{{ prod.description }}</h2>

</div>

{% include 'footer.phtml' %}